{
 "title": "Golbat",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "inter", "label": "Interval", "query": "1m,10m,30m,1h,6h,12h,1d,7d" },
   {
    "name": "area",
    "label": "Area",
    "query": {
     "query": "label_values(golbat_verified_pokemon_ttl, area) "
    }
   }
  ]
 },
 "panels": [
  { "title": "Basic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Verified Encounter Pokemon TTL & Resets / $area / $inter",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "expr": "avg(\n  avg(\n    increase(golbat_verified_pokemon_ttl{area=~\"$area\", type=\"encounter\", above30=\"0\"}[$inter]),\n    increase(golbat_verified_pokemon_ttl{area=~\"$area\", type=\"encounter\", above30=\"1\"}[$inter])\n  ) / avg(\n    increase(golbat_verified_pokemon_ttl_counter{area=~\"$area\", type=\"encounter\", above30=\"0\"}[$inter]),\n    increase(golbat_verified_pokemon_ttl_counter{area=~\"$area\", type=\"encounter\", above30=\"1\"}[$inter])\n    )\n)",
     "legendFormat": "TTL"
    },
    {
     "expr": "avg(\n  increase(golbat_verified_pokemon_ttl{area=~\"$area\", type=\"encounter\", above30=\"0\"}[$inter]) /\n  increase(golbat_verified_pokemon_ttl_counter{area=~\"$area\", type=\"encounter\", above30=\"0\"}[$inter])\n)",
     "legendFormat": "TTL 30m"
    },
    {
     "expr": "avg(\n  increase(golbat_verified_pokemon_ttl{area=~\"$area\", type=\"encounter\", above30=\"1\"}[$inter]) /\n  increase(golbat_verified_pokemon_ttl_counter{area=~\"$area\", type=\"encounter\", above30=\"1\"}[$inter])\n)",
     "legendFormat": "TTL 60m"
    },
    {
     "expr": "sum(increase(golbat_pokemon_stats_reset_count{area=~\"$area\"})[$inter])",
     "legendFormat": "Stats Reset"
    }
   ]
  },
  {
   "title": "Pokemon perfect rate / $area / $inter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "increase(sum(golbat_pokemon_count_hundo{area=~\"$area\"})[$inter])",
     "legendFormat": "Hundo"
    },
    {
     "expr": "increase(sum(golbat_pokemon_count_nundo{area=~\"$area\"})[$inter])",
     "legendFormat": "Nundo"
    }
   ]
  },
  {
   "title": "Raids rate / $area / $inter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (level) (increase(golbat_raid_count{area=~\"$area\"}[$inter]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prom Live",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total gyms / $inter",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "avg_over_time(golbat_gyms{in_battle=\"0\"}[$inter])",
       "legendFormat": "{{team}}"
      },
      {
       "expr": "avg_over_time(golbat_gyms{in_battle=\"1\"}[$inter])",
       "legendFormat": "Battle {{team}}"
      }
     ]
    },
    {
     "title": "Total incidents / $inter",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "targets": [
      {
       "expr": "avg_over_time(golbat_incidents[$inter])",
       "legendFormat": "{{kind}} {{confirmed}}"
      }
     ]
    },
    {
     "title": "Total lures / $inter",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "avg_over_time(golbat_lures[$inter])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Total raids / $inter",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "targets": [
      {
       "expr": "avg_over_time(golbat_raids[$inter])",
       "legendFormat": "{{level}}"
      }
     ]
    }
   ]
  },
  { "title": "Detailed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Pokemon rate / $area / $inter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(sum(golbat_pokemon_count_new{area=~\"$area\"})[$inter])",
     "legendFormat": "New"
    },
    {
     "expr": "increase(sum(golbat_pokemon_count_iv{area=~\"$area\"})[$inter])",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Multiple decode rate / $inter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "increase(golbat_decode_encounter[$inter])",
     "legendFormat": "Encounter ({{status}})"
    },
    {
     "expr": "increase(golbat_decode_fort_details[$inter])",
     "legendFormat": "FortDetails ({{status}})"
    },
    {
     "expr": "increase(golbat_decode_get_gym_info[$inter])",
     "legendFormat": "GetGymInfo ({{status}})"
    },
    {
     "expr": "increase(golbat_decode_get_map_forts[$inter])",
     "legendFormat": "GetMapForts ({{status}})"
    },
    {
     "expr": "increase(golbat_decode_social_action_with_request[$inter])",
     "legendFormat": "Social {{type}} ({{status}})"
    },
    {
     "expr": "increase(golbat_decode_disk_encounter[$inter])",
     "legendFormat": "DiskEncounter ({{status}})"
    },
    {
     "expr": "increase(golbat_decode_quest[$inter])",
     "legendFormat": "Quest ({{status}})"
    },
    {
     "expr": "increase(golbat_decode_get_friend_details[$inter])",
     "legendFormat": "GetFriendDetails ({{status}})"
    },
    {
     "expr": "increase(golbat_decode_search_player[$inter])",
     "legendFormat": "SearchPlayer ({{status}})"
    },
    {
     "expr": "increase(golbat_decode_start_incident[$inter])",
     "legendFormat": "StartIncident ({{status}})"
    },
    {
     "expr": "increase(golbat_decode_open_invasion[$inter])",
     "legendFormat": "OpenInvasion ({{status}})"
    }
   ]
  },
  {
   "title": "Quest decode rate / $inter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "increase(golbat_decode_quest{status=\"ok\"}[$inter])",
     "legendFormat": "{{message}}"
    },
    {
     "expr": "increase(golbat_decode_quest{status=\"error\"}[$inter])",
     "legendFormat": "{{message}}"
    }
   ]
  },
  {
   "title": "GMO sub-type sum rate / $inter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "increase(golbat_decode_gmo_type[$inter])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Incidents rate / $area / $inter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(sum(golbat_incident_count{area=~\"$area\"}[$inter]))",
     "legendFormat": "Incident"
    }
   ]
  },
  {
   "title": "RAW request rate / $inter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "increase(golbat_raw_requests{status=\"ok\"}[$inter])",
     "legendFormat": "OK"
    },
    {
     "expr": "increase(golbat_raw_requests{status!=\"ok\"}[$inter])",
     "legendFormat": "{{message}}"
    }
   ]
  },
  {
   "title": "Decode method rate / $inter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "increase(golbat_decode_methods{status=\"ok\"}[$inter])",
     "legendFormat": "{{method}} {{status}}"
    }
   ]
  },
  {
   "title": "Decode method rate / $inter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "increase(sum(golbat_pokemon_count_shiny))",
     "legendFormat": "{{method}} {{status}}"
    }
   ]
  }
 ]
}