// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: grpc/api.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GolbatApi_ScanPokemon_FullMethodName   = "/golbat_api.GolbatApi/ScanPokemon"
	GolbatApi_GetPokemon_FullMethodName    = "/golbat_api.GolbatApi/GetPokemon"
	GolbatApi_ScanGyms_FullMethodName      = "/golbat_api.GolbatApi/ScanGyms"
	GolbatApi_ScanPokestops_FullMethodName = "/golbat_api.GolbatApi/ScanPokestops"
	GolbatApi_ScanStations_FullMethodName  = "/golbat_api.GolbatApi/ScanStations"
	GolbatApi_ScanForts_FullMethodName     = "/golbat_api.GolbatApi/ScanForts"
)

// GolbatApiClient is the client API for GolbatApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GolbatApi is the gRPC counterpart of the HTTP /api scan endpoints. Every
// message mirrors the JSON request/response struct it is named after, field
// for field; decoder/api_grpc_parity_test.go enforces that. Semantics,
// auth and the differences from the JSON API are documented in api.md
// under "gRPC API".
type GolbatApiClient interface {
	// POST /api/pokemon/v3/scan
	ScanPokemon(ctx context.Context, in *PokemonScanRequest, opts ...grpc.CallOption) (*PokemonScanResponse, error)
	// GET /api/pokemon/id/{pokemon_id}, batched. Misses are omitted; match by id.
	GetPokemon(ctx context.Context, in *GetPokemonRequest, opts ...grpc.CallOption) (*GetPokemonResponse, error)
	// POST /api/gym/scan
	ScanGyms(ctx context.Context, in *FortScanRequest, opts ...grpc.CallOption) (*GymScanResponse, error)
	// POST /api/pokestop/scan
	ScanPokestops(ctx context.Context, in *FortScanRequest, opts ...grpc.CallOption) (*PokestopScanResponse, error)
	// POST /api/station/scan
	ScanStations(ctx context.Context, in *FortScanRequest, opts ...grpc.CallOption) (*StationScanResponse, error)
	// POST /api/fort/scan
	ScanForts(ctx context.Context, in *FortCombinedScanRequest, opts ...grpc.CallOption) (*FortScanResponse, error)
}

type golbatApiClient struct {
	cc grpc.ClientConnInterface
}

func NewGolbatApiClient(cc grpc.ClientConnInterface) GolbatApiClient {
	return &golbatApiClient{cc}
}

func (c *golbatApiClient) ScanPokemon(ctx context.Context, in *PokemonScanRequest, opts ...grpc.CallOption) (*PokemonScanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PokemonScanResponse)
	err := c.cc.Invoke(ctx, GolbatApi_ScanPokemon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *golbatApiClient) GetPokemon(ctx context.Context, in *GetPokemonRequest, opts ...grpc.CallOption) (*GetPokemonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPokemonResponse)
	err := c.cc.Invoke(ctx, GolbatApi_GetPokemon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *golbatApiClient) ScanGyms(ctx context.Context, in *FortScanRequest, opts ...grpc.CallOption) (*GymScanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GymScanResponse)
	err := c.cc.Invoke(ctx, GolbatApi_ScanGyms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *golbatApiClient) ScanPokestops(ctx context.Context, in *FortScanRequest, opts ...grpc.CallOption) (*PokestopScanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PokestopScanResponse)
	err := c.cc.Invoke(ctx, GolbatApi_ScanPokestops_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *golbatApiClient) ScanStations(ctx context.Context, in *FortScanRequest, opts ...grpc.CallOption) (*StationScanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StationScanResponse)
	err := c.cc.Invoke(ctx, GolbatApi_ScanStations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *golbatApiClient) ScanForts(ctx context.Context, in *FortCombinedScanRequest, opts ...grpc.CallOption) (*FortScanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FortScanResponse)
	err := c.cc.Invoke(ctx, GolbatApi_ScanForts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GolbatApiServer is the server API for GolbatApi service.
// All implementations must embed UnimplementedGolbatApiServer
// for forward compatibility.
//
// GolbatApi is the gRPC counterpart of the HTTP /api scan endpoints. Every
// message mirrors the JSON request/response struct it is named after, field
// for field; decoder/api_grpc_parity_test.go enforces that. Semantics,
// auth and the differences from the JSON API are documented in api.md
// under "gRPC API".
type GolbatApiServer interface {
	// POST /api/pokemon/v3/scan
	ScanPokemon(context.Context, *PokemonScanRequest) (*PokemonScanResponse, error)
	// GET /api/pokemon/id/{pokemon_id}, batched. Misses are omitted; match by id.
	GetPokemon(context.Context, *GetPokemonRequest) (*GetPokemonResponse, error)
	// POST /api/gym/scan
	ScanGyms(context.Context, *FortScanRequest) (*GymScanResponse, error)
	// POST /api/pokestop/scan
	ScanPokestops(context.Context, *FortScanRequest) (*PokestopScanResponse, error)
	// POST /api/station/scan
	ScanStations(context.Context, *FortScanRequest) (*StationScanResponse, error)
	// POST /api/fort/scan
	ScanForts(context.Context, *FortCombinedScanRequest) (*FortScanResponse, error)
	mustEmbedUnimplementedGolbatApiServer()
}

// UnimplementedGolbatApiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGolbatApiServer struct{}

func (UnimplementedGolbatApiServer) ScanPokemon(context.Context, *PokemonScanRequest) (*PokemonScanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ScanPokemon not implemented")
}
func (UnimplementedGolbatApiServer) GetPokemon(context.Context, *GetPokemonRequest) (*GetPokemonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPokemon not implemented")
}
func (UnimplementedGolbatApiServer) ScanGyms(context.Context, *FortScanRequest) (*GymScanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ScanGyms not implemented")
}
func (UnimplementedGolbatApiServer) ScanPokestops(context.Context, *FortScanRequest) (*PokestopScanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ScanPokestops not implemented")
}
func (UnimplementedGolbatApiServer) ScanStations(context.Context, *FortScanRequest) (*StationScanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ScanStations not implemented")
}
func (UnimplementedGolbatApiServer) ScanForts(context.Context, *FortCombinedScanRequest) (*FortScanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ScanForts not implemented")
}
func (UnimplementedGolbatApiServer) mustEmbedUnimplementedGolbatApiServer() {}
func (UnimplementedGolbatApiServer) testEmbeddedByValue()                   {}

// UnsafeGolbatApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GolbatApiServer will
// result in compilation errors.
type UnsafeGolbatApiServer interface {
	mustEmbedUnimplementedGolbatApiServer()
}

func RegisterGolbatApiServer(s grpc.ServiceRegistrar, srv GolbatApiServer) {
	// If the following call panics, it indicates UnimplementedGolbatApiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GolbatApi_ServiceDesc, srv)
}

func _GolbatApi_ScanPokemon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PokemonScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GolbatApiServer).ScanPokemon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GolbatApi_ScanPokemon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GolbatApiServer).ScanPokemon(ctx, req.(*PokemonScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GolbatApi_GetPokemon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPokemonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GolbatApiServer).GetPokemon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GolbatApi_GetPokemon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GolbatApiServer).GetPokemon(ctx, req.(*GetPokemonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GolbatApi_ScanGyms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FortScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GolbatApiServer).ScanGyms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GolbatApi_ScanGyms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GolbatApiServer).ScanGyms(ctx, req.(*FortScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GolbatApi_ScanPokestops_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FortScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GolbatApiServer).ScanPokestops(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GolbatApi_ScanPokestops_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GolbatApiServer).ScanPokestops(ctx, req.(*FortScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GolbatApi_ScanStations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FortScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GolbatApiServer).ScanStations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GolbatApi_ScanStations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GolbatApiServer).ScanStations(ctx, req.(*FortScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GolbatApi_ScanForts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FortCombinedScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GolbatApiServer).ScanForts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GolbatApi_ScanForts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GolbatApiServer).ScanForts(ctx, req.(*FortCombinedScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GolbatApi_ServiceDesc is the grpc.ServiceDesc for GolbatApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GolbatApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "golbat_api.GolbatApi",
	HandlerType: (*GolbatApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ScanPokemon",
			Handler:    _GolbatApi_ScanPokemon_Handler,
		},
		{
			MethodName: "GetPokemon",
			Handler:    _GolbatApi_GetPokemon_Handler,
		},
		{
			MethodName: "ScanGyms",
			Handler:    _GolbatApi_ScanGyms_Handler,
		},
		{
			MethodName: "ScanPokestops",
			Handler:    _GolbatApi_ScanPokestops_Handler,
		},
		{
			MethodName: "ScanStations",
			Handler:    _GolbatApi_ScanStations_Handler,
		},
		{
			MethodName: "ScanForts",
			Handler:    _GolbatApi_ScanForts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/api.proto",
}
