// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        v6.33.1
// source: grpc/pokemon_api.proto

//go:build protoopaque

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PokemonScanResponse_Status int32

const (
	PokemonScanResponse_UNSET   PokemonScanResponse_Status = 0
	PokemonScanResponse_SUCCESS PokemonScanResponse_Status = 200
)

// Enum value maps for PokemonScanResponse_Status.
var (
	PokemonScanResponse_Status_name = map[int32]string{
		0:   "UNSET",
		200: "SUCCESS",
	}
	PokemonScanResponse_Status_value = map[string]int32{
		"UNSET":   0,
		"SUCCESS": 200,
	}
)

func (x PokemonScanResponse_Status) Enum() *PokemonScanResponse_Status {
	p := new(PokemonScanResponse_Status)
	*p = x
	return p
}

func (x PokemonScanResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PokemonScanResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_pokemon_api_proto_enumTypes[0].Descriptor()
}

func (PokemonScanResponse_Status) Type() protoreflect.EnumType {
	return &file_grpc_pokemon_api_proto_enumTypes[0]
}

func (x PokemonScanResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type PokemonScanRequest struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_MinLat  float32                `protobuf:"fixed32,1,opt,name=min_lat,json=minLat,proto3" json:"min_lat,omitempty"`
	xxx_hidden_MinLon  float32                `protobuf:"fixed32,2,opt,name=min_lon,json=minLon,proto3" json:"min_lon,omitempty"`
	xxx_hidden_MaxLat  float32                `protobuf:"fixed32,3,opt,name=max_lat,json=maxLat,proto3" json:"max_lat,omitempty"`
	xxx_hidden_MaxLon  float32                `protobuf:"fixed32,4,opt,name=max_lon,json=maxLon,proto3" json:"max_lon,omitempty"`
	xxx_hidden_Limit   int32                  `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	xxx_hidden_Filters *[]*PokemonDnf         `protobuf:"bytes,7,rep,name=filters,proto3" json:"filters,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PokemonScanRequest) Reset() {
	*x = PokemonScanRequest{}
	mi := &file_grpc_pokemon_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PokemonScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PokemonScanRequest) ProtoMessage() {}

func (x *PokemonScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pokemon_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PokemonScanRequest) GetMinLat() float32 {
	if x != nil {
		return x.xxx_hidden_MinLat
	}
	return 0
}

func (x *PokemonScanRequest) GetMinLon() float32 {
	if x != nil {
		return x.xxx_hidden_MinLon
	}
	return 0
}

func (x *PokemonScanRequest) GetMaxLat() float32 {
	if x != nil {
		return x.xxx_hidden_MaxLat
	}
	return 0
}

func (x *PokemonScanRequest) GetMaxLon() float32 {
	if x != nil {
		return x.xxx_hidden_MaxLon
	}
	return 0
}

func (x *PokemonScanRequest) GetLimit() int32 {
	if x != nil {
		return x.xxx_hidden_Limit
	}
	return 0
}

func (x *PokemonScanRequest) GetFilters() []*PokemonDnf {
	if x != nil {
		if x.xxx_hidden_Filters != nil {
			return *x.xxx_hidden_Filters
		}
	}
	return nil
}

func (x *PokemonScanRequest) SetMinLat(v float32) {
	x.xxx_hidden_MinLat = v
}

func (x *PokemonScanRequest) SetMinLon(v float32) {
	x.xxx_hidden_MinLon = v
}

func (x *PokemonScanRequest) SetMaxLat(v float32) {
	x.xxx_hidden_MaxLat = v
}

func (x *PokemonScanRequest) SetMaxLon(v float32) {
	x.xxx_hidden_MaxLon = v
}

func (x *PokemonScanRequest) SetLimit(v int32) {
	x.xxx_hidden_Limit = v
}

func (x *PokemonScanRequest) SetFilters(v []*PokemonDnf) {
	x.xxx_hidden_Filters = &v
}

type PokemonScanRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	MinLat  float32
	MinLon  float32
	MaxLat  float32
	MaxLon  float32
	Limit   int32
	Filters []*PokemonDnf
}

func (b0 PokemonScanRequest_builder) Build() *PokemonScanRequest {
	m0 := &PokemonScanRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_MinLat = b.MinLat
	x.xxx_hidden_MinLon = b.MinLon
	x.xxx_hidden_MaxLat = b.MaxLat
	x.xxx_hidden_MaxLon = b.MaxLon
	x.xxx_hidden_Limit = b.Limit
	x.xxx_hidden_Filters = &b.Filters
	return m0
}

type PokemonDnf struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Pokemon          *[]*PokemonId          `protobuf:"bytes,1,rep,name=pokemon,proto3" json:"pokemon,omitempty"`
	xxx_hidden_Iv               *RangeMinMax           `protobuf:"bytes,2,opt,name=Iv,proto3,oneof" json:"Iv,omitempty"`
	xxx_hidden_AtkIv            *RangeMinMax           `protobuf:"bytes,3,opt,name=AtkIv,proto3,oneof" json:"AtkIv,omitempty"`
	xxx_hidden_DefIv            *RangeMinMax           `protobuf:"bytes,4,opt,name=DefIv,proto3,oneof" json:"DefIv,omitempty"`
	xxx_hidden_StaIv            *RangeMinMax           `protobuf:"bytes,5,opt,name=StaIv,proto3,oneof" json:"StaIv,omitempty"`
	xxx_hidden_Level            *RangeMinMax           `protobuf:"bytes,6,opt,name=Level,proto3,oneof" json:"Level,omitempty"`
	xxx_hidden_Cp               *RangeMinMax           `protobuf:"bytes,7,opt,name=Cp,proto3,oneof" json:"Cp,omitempty"`
	xxx_hidden_Gender           *RangeMinMax           `protobuf:"bytes,8,opt,name=Gender,proto3,oneof" json:"Gender,omitempty"`
	xxx_hidden_Size             *RangeMinMax           `protobuf:"bytes,9,opt,name=Size,proto3,oneof" json:"Size,omitempty"`
	xxx_hidden_PvpLittleRanking *RangeMinMax           `protobuf:"bytes,10,opt,name=PvpLittleRanking,proto3,oneof" json:"PvpLittleRanking,omitempty"`
	xxx_hidden_PvpGreatRanking  *RangeMinMax           `protobuf:"bytes,11,opt,name=PvpGreatRanking,proto3,oneof" json:"PvpGreatRanking,omitempty"`
	xxx_hidden_PvpUltraRanking  *RangeMinMax           `protobuf:"bytes,12,opt,name=PvpUltraRanking,proto3,oneof" json:"PvpUltraRanking,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *PokemonDnf) Reset() {
	*x = PokemonDnf{}
	mi := &file_grpc_pokemon_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PokemonDnf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PokemonDnf) ProtoMessage() {}

func (x *PokemonDnf) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pokemon_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PokemonDnf) GetPokemon() []*PokemonId {
	if x != nil {
		if x.xxx_hidden_Pokemon != nil {
			return *x.xxx_hidden_Pokemon
		}
	}
	return nil
}

func (x *PokemonDnf) GetIv() *RangeMinMax {
	if x != nil {
		return x.xxx_hidden_Iv
	}
	return nil
}

func (x *PokemonDnf) GetAtkIv() *RangeMinMax {
	if x != nil {
		return x.xxx_hidden_AtkIv
	}
	return nil
}

func (x *PokemonDnf) GetDefIv() *RangeMinMax {
	if x != nil {
		return x.xxx_hidden_DefIv
	}
	return nil
}

func (x *PokemonDnf) GetStaIv() *RangeMinMax {
	if x != nil {
		return x.xxx_hidden_StaIv
	}
	return nil
}

func (x *PokemonDnf) GetLevel() *RangeMinMax {
	if x != nil {
		return x.xxx_hidden_Level
	}
	return nil
}

func (x *PokemonDnf) GetCp() *RangeMinMax {
	if x != nil {
		return x.xxx_hidden_Cp
	}
	return nil
}

func (x *PokemonDnf) GetGender() *RangeMinMax {
	if x != nil {
		return x.xxx_hidden_Gender
	}
	return nil
}

func (x *PokemonDnf) GetSize() *RangeMinMax {
	if x != nil {
		return x.xxx_hidden_Size
	}
	return nil
}

func (x *PokemonDnf) GetPvpLittleRanking() *RangeMinMax {
	if x != nil {
		return x.xxx_hidden_PvpLittleRanking
	}
	return nil
}

func (x *PokemonDnf) GetPvpGreatRanking() *RangeMinMax {
	if x != nil {
		return x.xxx_hidden_PvpGreatRanking
	}
	return nil
}

func (x *PokemonDnf) GetPvpUltraRanking() *RangeMinMax {
	if x != nil {
		return x.xxx_hidden_PvpUltraRanking
	}
	return nil
}

func (x *PokemonDnf) SetPokemon(v []*PokemonId) {
	x.xxx_hidden_Pokemon = &v
}

func (x *PokemonDnf) SetIv(v *RangeMinMax) {
	x.xxx_hidden_Iv = v
}

func (x *PokemonDnf) SetAtkIv(v *RangeMinMax) {
	x.xxx_hidden_AtkIv = v
}

func (x *PokemonDnf) SetDefIv(v *RangeMinMax) {
	x.xxx_hidden_DefIv = v
}

func (x *PokemonDnf) SetStaIv(v *RangeMinMax) {
	x.xxx_hidden_StaIv = v
}

func (x *PokemonDnf) SetLevel(v *RangeMinMax) {
	x.xxx_hidden_Level = v
}

func (x *PokemonDnf) SetCp(v *RangeMinMax) {
	x.xxx_hidden_Cp = v
}

func (x *PokemonDnf) SetGender(v *RangeMinMax) {
	x.xxx_hidden_Gender = v
}

func (x *PokemonDnf) SetSize(v *RangeMinMax) {
	x.xxx_hidden_Size = v
}

func (x *PokemonDnf) SetPvpLittleRanking(v *RangeMinMax) {
	x.xxx_hidden_PvpLittleRanking = v
}

func (x *PokemonDnf) SetPvpGreatRanking(v *RangeMinMax) {
	x.xxx_hidden_PvpGreatRanking = v
}

func (x *PokemonDnf) SetPvpUltraRanking(v *RangeMinMax) {
	x.xxx_hidden_PvpUltraRanking = v
}

func (x *PokemonDnf) HasIv() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Iv != nil
}

func (x *PokemonDnf) HasAtkIv() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_AtkIv != nil
}

func (x *PokemonDnf) HasDefIv() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DefIv != nil
}

func (x *PokemonDnf) HasStaIv() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_StaIv != nil
}

func (x *PokemonDnf) HasLevel() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Level != nil
}

func (x *PokemonDnf) HasCp() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Cp != nil
}

func (x *PokemonDnf) HasGender() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Gender != nil
}

func (x *PokemonDnf) HasSize() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Size != nil
}

func (x *PokemonDnf) HasPvpLittleRanking() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_PvpLittleRanking != nil
}

func (x *PokemonDnf) HasPvpGreatRanking() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_PvpGreatRanking != nil
}

func (x *PokemonDnf) HasPvpUltraRanking() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_PvpUltraRanking != nil
}

func (x *PokemonDnf) ClearIv() {
	x.xxx_hidden_Iv = nil
}

func (x *PokemonDnf) ClearAtkIv() {
	x.xxx_hidden_AtkIv = nil
}

func (x *PokemonDnf) ClearDefIv() {
	x.xxx_hidden_DefIv = nil
}

func (x *PokemonDnf) ClearStaIv() {
	x.xxx_hidden_StaIv = nil
}

func (x *PokemonDnf) ClearLevel() {
	x.xxx_hidden_Level = nil
}

func (x *PokemonDnf) ClearCp() {
	x.xxx_hidden_Cp = nil
}

func (x *PokemonDnf) ClearGender() {
	x.xxx_hidden_Gender = nil
}

func (x *PokemonDnf) ClearSize() {
	x.xxx_hidden_Size = nil
}

func (x *PokemonDnf) ClearPvpLittleRanking() {
	x.xxx_hidden_PvpLittleRanking = nil
}

func (x *PokemonDnf) ClearPvpGreatRanking() {
	x.xxx_hidden_PvpGreatRanking = nil
}

func (x *PokemonDnf) ClearPvpUltraRanking() {
	x.xxx_hidden_PvpUltraRanking = nil
}

type PokemonDnf_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Pokemon          []*PokemonId
	Iv               *RangeMinMax
	AtkIv            *RangeMinMax
	DefIv            *RangeMinMax
	StaIv            *RangeMinMax
	Level            *RangeMinMax
	Cp               *RangeMinMax
	Gender           *RangeMinMax
	Size             *RangeMinMax
	PvpLittleRanking *RangeMinMax
	PvpGreatRanking  *RangeMinMax
	PvpUltraRanking  *RangeMinMax
}

func (b0 PokemonDnf_builder) Build() *PokemonDnf {
	m0 := &PokemonDnf{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Pokemon = &b.Pokemon
	x.xxx_hidden_Iv = b.Iv
	x.xxx_hidden_AtkIv = b.AtkIv
	x.xxx_hidden_DefIv = b.DefIv
	x.xxx_hidden_StaIv = b.StaIv
	x.xxx_hidden_Level = b.Level
	x.xxx_hidden_Cp = b.Cp
	x.xxx_hidden_Gender = b.Gender
	x.xxx_hidden_Size = b.Size
	x.xxx_hidden_PvpLittleRanking = b.PvpLittleRanking
	x.xxx_hidden_PvpGreatRanking = b.PvpGreatRanking
	x.xxx_hidden_PvpUltraRanking = b.PvpUltraRanking
	return m0
}

type PokemonId struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          int32                  `protobuf:"varint,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	xxx_hidden_Form        int32                  `protobuf:"varint,2,opt,name=form,proto3,oneof" json:"form,omitempty"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PokemonId) Reset() {
	*x = PokemonId{}
	mi := &file_grpc_pokemon_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PokemonId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PokemonId) ProtoMessage() {}

func (x *PokemonId) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pokemon_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PokemonId) GetId() int32 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *PokemonId) GetForm() int32 {
	if x != nil {
		return x.xxx_hidden_Form
	}
	return 0
}

func (x *PokemonId) SetId(v int32) {
	x.xxx_hidden_Id = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *PokemonId) SetForm(v int32) {
	x.xxx_hidden_Form = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *PokemonId) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *PokemonId) HasForm() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *PokemonId) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = 0
}

func (x *PokemonId) ClearForm() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Form = 0
}

type PokemonId_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id   *int32
	Form *int32
}

func (b0 PokemonId_builder) Build() *PokemonId {
	m0 := &PokemonId{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Id = *b.Id
	}
	if b.Form != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Form = *b.Form
	}
	return m0
}

type RangeMinMax struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Min         int32                  `protobuf:"varint,1,opt,name=min,proto3,oneof" json:"min,omitempty"`
	xxx_hidden_Max         int32                  `protobuf:"varint,2,opt,name=max,proto3,oneof" json:"max,omitempty"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RangeMinMax) Reset() {
	*x = RangeMinMax{}
	mi := &file_grpc_pokemon_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeMinMax) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeMinMax) ProtoMessage() {}

func (x *RangeMinMax) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pokemon_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RangeMinMax) GetMin() int32 {
	if x != nil {
		return x.xxx_hidden_Min
	}
	return 0
}

func (x *RangeMinMax) GetMax() int32 {
	if x != nil {
		return x.xxx_hidden_Max
	}
	return 0
}

func (x *RangeMinMax) SetMin(v int32) {
	x.xxx_hidden_Min = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *RangeMinMax) SetMax(v int32) {
	x.xxx_hidden_Max = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *RangeMinMax) HasMin() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RangeMinMax) HasMax() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *RangeMinMax) ClearMin() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Min = 0
}

func (x *RangeMinMax) ClearMax() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Max = 0
}

type RangeMinMax_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Min *int32
	Max *int32
}

func (b0 RangeMinMax_builder) Build() *RangeMinMax {
	m0 := &RangeMinMax{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Min != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Min = *b.Min
	}
	if b.Max != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Max = *b.Max
	}
	return m0
}

type PokemonScanResponse struct {
	state              protoimpl.MessageState     `protogen:"opaque.v1"`
	xxx_hidden_Status  PokemonScanResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=pokemon_api.PokemonScanResponse_Status" json:"status,omitempty"`
	xxx_hidden_Pokemon *[]*PokemonDetails         `protobuf:"bytes,2,rep,name=pokemon,proto3" json:"pokemon,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PokemonScanResponse) Reset() {
	*x = PokemonScanResponse{}
	mi := &file_grpc_pokemon_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PokemonScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PokemonScanResponse) ProtoMessage() {}

func (x *PokemonScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pokemon_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PokemonScanResponse) GetStatus() PokemonScanResponse_Status {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return PokemonScanResponse_UNSET
}

func (x *PokemonScanResponse) GetPokemon() []*PokemonDetails {
	if x != nil {
		if x.xxx_hidden_Pokemon != nil {
			return *x.xxx_hidden_Pokemon
		}
	}
	return nil
}

func (x *PokemonScanResponse) SetStatus(v PokemonScanResponse_Status) {
	x.xxx_hidden_Status = v
}

func (x *PokemonScanResponse) SetPokemon(v []*PokemonDetails) {
	x.xxx_hidden_Pokemon = &v
}

type PokemonScanResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Status  PokemonScanResponse_Status
	Pokemon []*PokemonDetails
}

func (b0 PokemonScanResponse_builder) Build() *PokemonScanResponse {
	m0 := &PokemonScanResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Status = b.Status
	x.xxx_hidden_Pokemon = &b.Pokemon
	return m0
}

type PokemonDetails struct {
	state                              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id                      uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	xxx_hidden_PokestopId              *string                `protobuf:"bytes,2,opt,name=pokestop_id,json=pokestopId,proto3,oneof" json:"pokestop_id,omitempty"`
	xxx_hidden_SpawnId                 int64                  `protobuf:"varint,3,opt,name=spawn_id,json=spawnId,proto3,oneof" json:"spawn_id,omitempty"`
	xxx_hidden_Lat                     float64                `protobuf:"fixed64,4,opt,name=lat,proto3" json:"lat,omitempty"`
	xxx_hidden_Lon                     float64                `protobuf:"fixed64,5,opt,name=lon,proto3" json:"lon,omitempty"`
	xxx_hidden_Weight                  float32                `protobuf:"fixed32,6,opt,name=weight,proto3,oneof" json:"weight,omitempty"`
	xxx_hidden_Size                    int32                  `protobuf:"varint,7,opt,name=size,proto3,oneof" json:"size,omitempty"`
	xxx_hidden_Height                  float32                `protobuf:"fixed32,8,opt,name=height,proto3,oneof" json:"height,omitempty"`
	xxx_hidden_ExpireTimestamp         int32                  `protobuf:"varint,9,opt,name=expire_timestamp,json=expireTimestamp,proto3,oneof" json:"expire_timestamp,omitempty"`
	xxx_hidden_Updated                 int32                  `protobuf:"varint,10,opt,name=updated,proto3,oneof" json:"updated,omitempty"`
	xxx_hidden_PokemonId               int32                  `protobuf:"varint,11,opt,name=pokemon_id,json=pokemonId,proto3,oneof" json:"pokemon_id,omitempty"`
	xxx_hidden_Move_1                  int32                  `protobuf:"varint,12,opt,name=move_1,json=move1,proto3,oneof" json:"move_1,omitempty"`
	xxx_hidden_Move_2                  int32                  `protobuf:"varint,13,opt,name=move_2,json=move2,proto3,oneof" json:"move_2,omitempty"`
	xxx_hidden_Gender                  int32                  `protobuf:"varint,14,opt,name=gender,proto3,oneof" json:"gender,omitempty"`
	xxx_hidden_Cp                      int32                  `protobuf:"varint,15,opt,name=cp,proto3,oneof" json:"cp,omitempty"`
	xxx_hidden_AtkIv                   int32                  `protobuf:"varint,16,opt,name=atk_iv,json=atkIv,proto3,oneof" json:"atk_iv,omitempty"`
	xxx_hidden_DefIv                   int32                  `protobuf:"varint,17,opt,name=def_iv,json=defIv,proto3,oneof" json:"def_iv,omitempty"`
	xxx_hidden_StaIv                   int32                  `protobuf:"varint,18,opt,name=sta_iv,json=staIv,proto3,oneof" json:"sta_iv,omitempty"`
	xxx_hidden_Iv                      float32                `protobuf:"fixed32,19,opt,name=iv,proto3,oneof" json:"iv,omitempty"`
	xxx_hidden_Form                    int32                  `protobuf:"varint,20,opt,name=form,proto3,oneof" json:"form,omitempty"`
	xxx_hidden_Level                   int32                  `protobuf:"varint,21,opt,name=level,proto3,oneof" json:"level,omitempty"`
	xxx_hidden_EncounterWeather        int32                  `protobuf:"varint,22,opt,name=encounter_weather,json=encounterWeather,proto3,oneof" json:"encounter_weather,omitempty"`
	xxx_hidden_Weather                 int32                  `protobuf:"varint,23,opt,name=weather,proto3,oneof" json:"weather,omitempty"`
	xxx_hidden_Costume                 int32                  `protobuf:"varint,24,opt,name=costume,proto3,oneof" json:"costume,omitempty"`
	xxx_hidden_FirstSeenTimestamp      int64                  `protobuf:"varint,25,opt,name=first_seen_timestamp,json=firstSeenTimestamp,proto3,oneof" json:"first_seen_timestamp,omitempty"`
	xxx_hidden_Changed                 int32                  `protobuf:"varint,26,opt,name=changed,proto3,oneof" json:"changed,omitempty"`
	xxx_hidden_CellId                  int64                  `protobuf:"varint,27,opt,name=cell_id,json=cellId,proto3,oneof" json:"cell_id,omitempty"`
	xxx_hidden_ExpireTimestampVerified bool                   `protobuf:"varint,28,opt,name=expire_timestamp_verified,json=expireTimestampVerified,proto3" json:"expire_timestamp_verified,omitempty"`
	xxx_hidden_DisplayPokemonId        int32                  `protobuf:"varint,29,opt,name=display_pokemon_id,json=displayPokemonId,proto3,oneof" json:"display_pokemon_id,omitempty"`
	xxx_hidden_IsDitto                 bool                   `protobuf:"varint,30,opt,name=is_ditto,json=isDitto,proto3,oneof" json:"is_ditto,omitempty"`
	xxx_hidden_SeenType                *string                `protobuf:"bytes,31,opt,name=seen_type,json=seenType,proto3,oneof" json:"seen_type,omitempty"`
	xxx_hidden_Shiny                   bool                   `protobuf:"varint,32,opt,name=shiny,proto3,oneof" json:"shiny,omitempty"`
	xxx_hidden_Username                *string                `protobuf:"bytes,33,opt,name=username,proto3,oneof" json:"username,omitempty"`
	xxx_hidden_Capture_1               float32                `protobuf:"fixed32,34,opt,name=capture_1,json=capture1,proto3,oneof" json:"capture_1,omitempty"`
	xxx_hidden_Capture_2               float32                `protobuf:"fixed32,35,opt,name=capture_2,json=capture2,proto3,oneof" json:"capture_2,omitempty"`
	xxx_hidden_Capture_3               float32                `protobuf:"fixed32,36,opt,name=capture_3,json=capture3,proto3,oneof" json:"capture_3,omitempty"`
	xxx_hidden_Pvp                     *string                `protobuf:"bytes,37,opt,name=pvp,proto3,oneof" json:"pvp,omitempty"`
	xxx_hidden_Distance                float32                `protobuf:"fixed32,38,opt,name=distance,proto3,oneof" json:"distance,omitempty"`
	XXX_raceDetectHookData             protoimpl.RaceDetectHookData
	XXX_presence                       [2]uint32
	unknownFields                      protoimpl.UnknownFields
	sizeCache                          protoimpl.SizeCache
}

func (x *PokemonDetails) Reset() {
	*x = PokemonDetails{}
	mi := &file_grpc_pokemon_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PokemonDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PokemonDetails) ProtoMessage() {}

func (x *PokemonDetails) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pokemon_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PokemonDetails) GetId() uint64 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *PokemonDetails) GetPokestopId() string {
	if x != nil {
		if x.xxx_hidden_PokestopId != nil {
			return *x.xxx_hidden_PokestopId
		}
		return ""
	}
	return ""
}

func (x *PokemonDetails) GetSpawnId() int64 {
	if x != nil {
		return x.xxx_hidden_SpawnId
	}
	return 0
}

func (x *PokemonDetails) GetLat() float64 {
	if x != nil {
		return x.xxx_hidden_Lat
	}
	return 0
}

func (x *PokemonDetails) GetLon() float64 {
	if x != nil {
		return x.xxx_hidden_Lon
	}
	return 0
}

func (x *PokemonDetails) GetWeight() float32 {
	if x != nil {
		return x.xxx_hidden_Weight
	}
	return 0
}

func (x *PokemonDetails) GetSize() int32 {
	if x != nil {
		return x.xxx_hidden_Size
	}
	return 0
}

func (x *PokemonDetails) GetHeight() float32 {
	if x != nil {
		return x.xxx_hidden_Height
	}
	return 0
}

func (x *PokemonDetails) GetExpireTimestamp() int32 {
	if x != nil {
		return x.xxx_hidden_ExpireTimestamp
	}
	return 0
}

func (x *PokemonDetails) GetUpdated() int32 {
	if x != nil {
		return x.xxx_hidden_Updated
	}
	return 0
}

func (x *PokemonDetails) GetPokemonId() int32 {
	if x != nil {
		return x.xxx_hidden_PokemonId
	}
	return 0
}

func (x *PokemonDetails) GetMove_1() int32 {
	if x != nil {
		return x.xxx_hidden_Move_1
	}
	return 0
}

func (x *PokemonDetails) GetMove_2() int32 {
	if x != nil {
		return x.xxx_hidden_Move_2
	}
	return 0
}

func (x *PokemonDetails) GetGender() int32 {
	if x != nil {
		return x.xxx_hidden_Gender
	}
	return 0
}

func (x *PokemonDetails) GetCp() int32 {
	if x != nil {
		return x.xxx_hidden_Cp
	}
	return 0
}

func (x *PokemonDetails) GetAtkIv() int32 {
	if x != nil {
		return x.xxx_hidden_AtkIv
	}
	return 0
}

func (x *PokemonDetails) GetDefIv() int32 {
	if x != nil {
		return x.xxx_hidden_DefIv
	}
	return 0
}

func (x *PokemonDetails) GetStaIv() int32 {
	if x != nil {
		return x.xxx_hidden_StaIv
	}
	return 0
}

func (x *PokemonDetails) GetIv() float32 {
	if x != nil {
		return x.xxx_hidden_Iv
	}
	return 0
}

func (x *PokemonDetails) GetForm() int32 {
	if x != nil {
		return x.xxx_hidden_Form
	}
	return 0
}

func (x *PokemonDetails) GetLevel() int32 {
	if x != nil {
		return x.xxx_hidden_Level
	}
	return 0
}

func (x *PokemonDetails) GetEncounterWeather() int32 {
	if x != nil {
		return x.xxx_hidden_EncounterWeather
	}
	return 0
}

func (x *PokemonDetails) GetWeather() int32 {
	if x != nil {
		return x.xxx_hidden_Weather
	}
	return 0
}

func (x *PokemonDetails) GetCostume() int32 {
	if x != nil {
		return x.xxx_hidden_Costume
	}
	return 0
}

func (x *PokemonDetails) GetFirstSeenTimestamp() int64 {
	if x != nil {
		return x.xxx_hidden_FirstSeenTimestamp
	}
	return 0
}

func (x *PokemonDetails) GetChanged() int32 {
	if x != nil {
		return x.xxx_hidden_Changed
	}
	return 0
}

func (x *PokemonDetails) GetCellId() int64 {
	if x != nil {
		return x.xxx_hidden_CellId
	}
	return 0
}

func (x *PokemonDetails) GetExpireTimestampVerified() bool {
	if x != nil {
		return x.xxx_hidden_ExpireTimestampVerified
	}
	return false
}

func (x *PokemonDetails) GetDisplayPokemonId() int32 {
	if x != nil {
		return x.xxx_hidden_DisplayPokemonId
	}
	return 0
}

func (x *PokemonDetails) GetIsDitto() bool {
	if x != nil {
		return x.xxx_hidden_IsDitto
	}
	return false
}

func (x *PokemonDetails) GetSeenType() string {
	if x != nil {
		if x.xxx_hidden_SeenType != nil {
			return *x.xxx_hidden_SeenType
		}
		return ""
	}
	return ""
}

func (x *PokemonDetails) GetShiny() bool {
	if x != nil {
		return x.xxx_hidden_Shiny
	}
	return false
}

func (x *PokemonDetails) GetUsername() string {
	if x != nil {
		if x.xxx_hidden_Username != nil {
			return *x.xxx_hidden_Username
		}
		return ""
	}
	return ""
}

func (x *PokemonDetails) GetCapture_1() float32 {
	if x != nil {
		return x.xxx_hidden_Capture_1
	}
	return 0
}

func (x *PokemonDetails) GetCapture_2() float32 {
	if x != nil {
		return x.xxx_hidden_Capture_2
	}
	return 0
}

func (x *PokemonDetails) GetCapture_3() float32 {
	if x != nil {
		return x.xxx_hidden_Capture_3
	}
	return 0
}

func (x *PokemonDetails) GetPvp() string {
	if x != nil {
		if x.xxx_hidden_Pvp != nil {
			return *x.xxx_hidden_Pvp
		}
		return ""
	}
	return ""
}

func (x *PokemonDetails) GetDistance() float32 {
	if x != nil {
		return x.xxx_hidden_Distance
	}
	return 0
}

func (x *PokemonDetails) SetId(v uint64) {
	x.xxx_hidden_Id = v
}

func (x *PokemonDetails) SetPokestopId(v string) {
	x.xxx_hidden_PokestopId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 38)
}

func (x *PokemonDetails) SetSpawnId(v int64) {
	x.xxx_hidden_SpawnId = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 38)
}

func (x *PokemonDetails) SetLat(v float64) {
	x.xxx_hidden_Lat = v
}

func (x *PokemonDetails) SetLon(v float64) {
	x.xxx_hidden_Lon = v
}

func (x *PokemonDetails) SetWeight(v float32) {
	x.xxx_hidden_Weight = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 38)
}

func (x *PokemonDetails) SetSize(v int32) {
	x.xxx_hidden_Size = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 38)
}

func (x *PokemonDetails) SetHeight(v float32) {
	x.xxx_hidden_Height = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 38)
}

func (x *PokemonDetails) SetExpireTimestamp(v int32) {
	x.xxx_hidden_ExpireTimestamp = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 38)
}

func (x *PokemonDetails) SetUpdated(v int32) {
	x.xxx_hidden_Updated = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 9, 38)
}

func (x *PokemonDetails) SetPokemonId(v int32) {
	x.xxx_hidden_PokemonId = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 10, 38)
}

func (x *PokemonDetails) SetMove_1(v int32) {
	x.xxx_hidden_Move_1 = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 11, 38)
}

func (x *PokemonDetails) SetMove_2(v int32) {
	x.xxx_hidden_Move_2 = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 12, 38)
}

func (x *PokemonDetails) SetGender(v int32) {
	x.xxx_hidden_Gender = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 13, 38)
}

func (x *PokemonDetails) SetCp(v int32) {
	x.xxx_hidden_Cp = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 14, 38)
}

func (x *PokemonDetails) SetAtkIv(v int32) {
	x.xxx_hidden_AtkIv = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 15, 38)
}

func (x *PokemonDetails) SetDefIv(v int32) {
	x.xxx_hidden_DefIv = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 16, 38)
}

func (x *PokemonDetails) SetStaIv(v int32) {
	x.xxx_hidden_StaIv = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 17, 38)
}

func (x *PokemonDetails) SetIv(v float32) {
	x.xxx_hidden_Iv = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 18, 38)
}

func (x *PokemonDetails) SetForm(v int32) {
	x.xxx_hidden_Form = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 19, 38)
}

func (x *PokemonDetails) SetLevel(v int32) {
	x.xxx_hidden_Level = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 20, 38)
}

func (x *PokemonDetails) SetEncounterWeather(v int32) {
	x.xxx_hidden_EncounterWeather = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 21, 38)
}

func (x *PokemonDetails) SetWeather(v int32) {
	x.xxx_hidden_Weather = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 22, 38)
}

func (x *PokemonDetails) SetCostume(v int32) {
	x.xxx_hidden_Costume = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 23, 38)
}

func (x *PokemonDetails) SetFirstSeenTimestamp(v int64) {
	x.xxx_hidden_FirstSeenTimestamp = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 24, 38)
}

func (x *PokemonDetails) SetChanged(v int32) {
	x.xxx_hidden_Changed = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 25, 38)
}

func (x *PokemonDetails) SetCellId(v int64) {
	x.xxx_hidden_CellId = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 26, 38)
}

func (x *PokemonDetails) SetExpireTimestampVerified(v bool) {
	x.xxx_hidden_ExpireTimestampVerified = v
}

func (x *PokemonDetails) SetDisplayPokemonId(v int32) {
	x.xxx_hidden_DisplayPokemonId = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 28, 38)
}

func (x *PokemonDetails) SetIsDitto(v bool) {
	x.xxx_hidden_IsDitto = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 29, 38)
}

func (x *PokemonDetails) SetSeenType(v string) {
	x.xxx_hidden_SeenType = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 30, 38)
}

func (x *PokemonDetails) SetShiny(v bool) {
	x.xxx_hidden_Shiny = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 31, 38)
}

func (x *PokemonDetails) SetUsername(v string) {
	x.xxx_hidden_Username = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[1]), 32, 38)
}

func (x *PokemonDetails) SetCapture_1(v float32) {
	x.xxx_hidden_Capture_1 = v
	protoimpl.X.SetPresent(&(x.XXX_presence[1]), 33, 38)
}

func (x *PokemonDetails) SetCapture_2(v float32) {
	x.xxx_hidden_Capture_2 = v
	protoimpl.X.SetPresent(&(x.XXX_presence[1]), 34, 38)
}

func (x *PokemonDetails) SetCapture_3(v float32) {
	x.xxx_hidden_Capture_3 = v
	protoimpl.X.SetPresent(&(x.XXX_presence[1]), 35, 38)
}

func (x *PokemonDetails) SetPvp(v string) {
	x.xxx_hidden_Pvp = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[1]), 36, 38)
}

func (x *PokemonDetails) SetDistance(v float32) {
	x.xxx_hidden_Distance = v
	protoimpl.X.SetPresent(&(x.XXX_presence[1]), 37, 38)
}

func (x *PokemonDetails) HasPokestopId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *PokemonDetails) HasSpawnId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *PokemonDetails) HasWeight() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *PokemonDetails) HasSize() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *PokemonDetails) HasHeight() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *PokemonDetails) HasExpireTimestamp() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *PokemonDetails) HasUpdated() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 9)
}

func (x *PokemonDetails) HasPokemonId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 10)
}

func (x *PokemonDetails) HasMove_1() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 11)
}

func (x *PokemonDetails) HasMove_2() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 12)
}

func (x *PokemonDetails) HasGender() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 13)
}

func (x *PokemonDetails) HasCp() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 14)
}

func (x *PokemonDetails) HasAtkIv() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 15)
}

func (x *PokemonDetails) HasDefIv() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 16)
}

func (x *PokemonDetails) HasStaIv() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 17)
}

func (x *PokemonDetails) HasIv() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 18)
}

func (x *PokemonDetails) HasForm() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 19)
}

func (x *PokemonDetails) HasLevel() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 20)
}

func (x *PokemonDetails) HasEncounterWeather() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 21)
}

func (x *PokemonDetails) HasWeather() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 22)
}

func (x *PokemonDetails) HasCostume() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 23)
}

func (x *PokemonDetails) HasFirstSeenTimestamp() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 24)
}

func (x *PokemonDetails) HasChanged() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 25)
}

func (x *PokemonDetails) HasCellId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 26)
}

func (x *PokemonDetails) HasDisplayPokemonId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 28)
}

func (x *PokemonDetails) HasIsDitto() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 29)
}

func (x *PokemonDetails) HasSeenType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 30)
}

func (x *PokemonDetails) HasShiny() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 31)
}

func (x *PokemonDetails) HasUsername() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[1]), 32)
}

func (x *PokemonDetails) HasCapture_1() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[1]), 33)
}

func (x *PokemonDetails) HasCapture_2() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[1]), 34)
}

func (x *PokemonDetails) HasCapture_3() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[1]), 35)
}

func (x *PokemonDetails) HasPvp() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[1]), 36)
}

func (x *PokemonDetails) HasDistance() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[1]), 37)
}

func (x *PokemonDetails) ClearPokestopId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_PokestopId = nil
}

func (x *PokemonDetails) ClearSpawnId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_SpawnId = 0
}

func (x *PokemonDetails) ClearWeight() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Weight = 0
}

func (x *PokemonDetails) ClearSize() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_Size = 0
}

func (x *PokemonDetails) ClearHeight() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_Height = 0
}

func (x *PokemonDetails) ClearExpireTimestamp() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_ExpireTimestamp = 0
}

func (x *PokemonDetails) ClearUpdated() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 9)
	x.xxx_hidden_Updated = 0
}

func (x *PokemonDetails) ClearPokemonId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 10)
	x.xxx_hidden_PokemonId = 0
}

func (x *PokemonDetails) ClearMove_1() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 11)
	x.xxx_hidden_Move_1 = 0
}

func (x *PokemonDetails) ClearMove_2() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 12)
	x.xxx_hidden_Move_2 = 0
}

func (x *PokemonDetails) ClearGender() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 13)
	x.xxx_hidden_Gender = 0
}

func (x *PokemonDetails) ClearCp() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 14)
	x.xxx_hidden_Cp = 0
}

func (x *PokemonDetails) ClearAtkIv() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 15)
	x.xxx_hidden_AtkIv = 0
}

func (x *PokemonDetails) ClearDefIv() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 16)
	x.xxx_hidden_DefIv = 0
}

func (x *PokemonDetails) ClearStaIv() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 17)
	x.xxx_hidden_StaIv = 0
}

func (x *PokemonDetails) ClearIv() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 18)
	x.xxx_hidden_Iv = 0
}

func (x *PokemonDetails) ClearForm() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 19)
	x.xxx_hidden_Form = 0
}

func (x *PokemonDetails) ClearLevel() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 20)
	x.xxx_hidden_Level = 0
}

func (x *PokemonDetails) ClearEncounterWeather() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 21)
	x.xxx_hidden_EncounterWeather = 0
}

func (x *PokemonDetails) ClearWeather() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 22)
	x.xxx_hidden_Weather = 0
}

func (x *PokemonDetails) ClearCostume() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 23)
	x.xxx_hidden_Costume = 0
}

func (x *PokemonDetails) ClearFirstSeenTimestamp() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 24)
	x.xxx_hidden_FirstSeenTimestamp = 0
}

func (x *PokemonDetails) ClearChanged() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 25)
	x.xxx_hidden_Changed = 0
}

func (x *PokemonDetails) ClearCellId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 26)
	x.xxx_hidden_CellId = 0
}

func (x *PokemonDetails) ClearDisplayPokemonId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 28)
	x.xxx_hidden_DisplayPokemonId = 0
}

func (x *PokemonDetails) ClearIsDitto() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 29)
	x.xxx_hidden_IsDitto = false
}

func (x *PokemonDetails) ClearSeenType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 30)
	x.xxx_hidden_SeenType = nil
}

func (x *PokemonDetails) ClearShiny() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 31)
	x.xxx_hidden_Shiny = false
}

func (x *PokemonDetails) ClearUsername() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[1]), 32)
	x.xxx_hidden_Username = nil
}

func (x *PokemonDetails) ClearCapture_1() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[1]), 33)
	x.xxx_hidden_Capture_1 = 0
}

func (x *PokemonDetails) ClearCapture_2() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[1]), 34)
	x.xxx_hidden_Capture_2 = 0
}

func (x *PokemonDetails) ClearCapture_3() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[1]), 35)
	x.xxx_hidden_Capture_3 = 0
}

func (x *PokemonDetails) ClearPvp() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[1]), 36)
	x.xxx_hidden_Pvp = nil
}

func (x *PokemonDetails) ClearDistance() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[1]), 37)
	x.xxx_hidden_Distance = 0
}

type PokemonDetails_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id                      uint64
	PokestopId              *string
	SpawnId                 *int64
	Lat                     float64
	Lon                     float64
	Weight                  *float32
	Size                    *int32
	Height                  *float32
	ExpireTimestamp         *int32
	Updated                 *int32
	PokemonId               *int32
	Move_1                  *int32
	Move_2                  *int32
	Gender                  *int32
	Cp                      *int32
	AtkIv                   *int32
	DefIv                   *int32
	StaIv                   *int32
	Iv                      *float32
	Form                    *int32
	Level                   *int32
	EncounterWeather        *int32
	Weather                 *int32
	Costume                 *int32
	FirstSeenTimestamp      *int64
	Changed                 *int32
	CellId                  *int64
	ExpireTimestampVerified bool
	DisplayPokemonId        *int32
	IsDitto                 *bool
	SeenType                *string
	Shiny                   *bool
	Username                *string
	Capture_1               *float32
	Capture_2               *float32
	Capture_3               *float32
	Pvp                     *string
	Distance                *float32
}

func (b0 PokemonDetails_builder) Build() *PokemonDetails {
	m0 := &PokemonDetails{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	if b.PokestopId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 38)
		x.xxx_hidden_PokestopId = b.PokestopId
	}
	if b.SpawnId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 38)
		x.xxx_hidden_SpawnId = *b.SpawnId
	}
	x.xxx_hidden_Lat = b.Lat
	x.xxx_hidden_Lon = b.Lon
	if b.Weight != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 38)
		x.xxx_hidden_Weight = *b.Weight
	}
	if b.Size != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 38)
		x.xxx_hidden_Size = *b.Size
	}
	if b.Height != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 38)
		x.xxx_hidden_Height = *b.Height
	}
	if b.ExpireTimestamp != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 38)
		x.xxx_hidden_ExpireTimestamp = *b.ExpireTimestamp
	}
	if b.Updated != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 9, 38)
		x.xxx_hidden_Updated = *b.Updated
	}
	if b.PokemonId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 10, 38)
		x.xxx_hidden_PokemonId = *b.PokemonId
	}
	if b.Move_1 != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 11, 38)
		x.xxx_hidden_Move_1 = *b.Move_1
	}
	if b.Move_2 != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 12, 38)
		x.xxx_hidden_Move_2 = *b.Move_2
	}
	if b.Gender != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 13, 38)
		x.xxx_hidden_Gender = *b.Gender
	}
	if b.Cp != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 14, 38)
		x.xxx_hidden_Cp = *b.Cp
	}
	if b.AtkIv != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 15, 38)
		x.xxx_hidden_AtkIv = *b.AtkIv
	}
	if b.DefIv != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 16, 38)
		x.xxx_hidden_DefIv = *b.DefIv
	}
	if b.StaIv != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 17, 38)
		x.xxx_hidden_StaIv = *b.StaIv
	}
	if b.Iv != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 18, 38)
		x.xxx_hidden_Iv = *b.Iv
	}
	if b.Form != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 19, 38)
		x.xxx_hidden_Form = *b.Form
	}
	if b.Level != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 20, 38)
		x.xxx_hidden_Level = *b.Level
	}
	if b.EncounterWeather != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 21, 38)
		x.xxx_hidden_EncounterWeather = *b.EncounterWeather
	}
	if b.Weather != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 22, 38)
		x.xxx_hidden_Weather = *b.Weather
	}
	if b.Costume != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 23, 38)
		x.xxx_hidden_Costume = *b.Costume
	}
	if b.FirstSeenTimestamp != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 24, 38)
		x.xxx_hidden_FirstSeenTimestamp = *b.FirstSeenTimestamp
	}
	if b.Changed != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 25, 38)
		x.xxx_hidden_Changed = *b.Changed
	}
	if b.CellId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 26, 38)
		x.xxx_hidden_CellId = *b.CellId
	}
	x.xxx_hidden_ExpireTimestampVerified = b.ExpireTimestampVerified
	if b.DisplayPokemonId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 28, 38)
		x.xxx_hidden_DisplayPokemonId = *b.DisplayPokemonId
	}
	if b.IsDitto != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 29, 38)
		x.xxx_hidden_IsDitto = *b.IsDitto
	}
	if b.SeenType != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 30, 38)
		x.xxx_hidden_SeenType = b.SeenType
	}
	if b.Shiny != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 31, 38)
		x.xxx_hidden_Shiny = *b.Shiny
	}
	if b.Username != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[1]), 32, 38)
		x.xxx_hidden_Username = b.Username
	}
	if b.Capture_1 != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[1]), 33, 38)
		x.xxx_hidden_Capture_1 = *b.Capture_1
	}
	if b.Capture_2 != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[1]), 34, 38)
		x.xxx_hidden_Capture_2 = *b.Capture_2
	}
	if b.Capture_3 != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[1]), 35, 38)
		x.xxx_hidden_Capture_3 = *b.Capture_3
	}
	if b.Pvp != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[1]), 36, 38)
		x.xxx_hidden_Pvp = b.Pvp
	}
	if b.Distance != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[1]), 37, 38)
		x.xxx_hidden_Distance = *b.Distance
	}
	return m0
}

var File_grpc_pokemon_api_proto protoreflect.FileDescriptor

var file_grpc_pokemon_api_proto_rawDesc = []byte{
	0x0a, 0x16, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x5f, 0x61,
	0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f,
	0x6e, 0x5f, 0x61, 0x70, 0x69, 0x22, 0xc1, 0x01, 0x0a, 0x12, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f,
	0x6e, 0x53, 0x63, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x6d, 0x69, 0x6e, 0x5f, 0x6c, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x6d,
	0x69, 0x6e, 0x4c, 0x61, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x6d, 0x69, 0x6e, 0x5f, 0x6c, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x6d, 0x69, 0x6e, 0x4c, 0x6f, 0x6e, 0x12, 0x17,
	0x0a, 0x07, 0x6d, 0x61, 0x78, 0x5f, 0x6c, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x06, 0x6d, 0x61, 0x78, 0x4c, 0x61, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x6d, 0x61, 0x78, 0x5f, 0x6c,
	0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x6d, 0x61, 0x78, 0x4c, 0x6f, 0x6e,
	0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x31, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f,
	0x6e, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x44, 0x6e, 0x66,
	0x52, 0x07, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x22, 0xbe, 0x06, 0x0a, 0x0a, 0x50, 0x6f,
	0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x44, 0x6e, 0x66, 0x12, 0x30, 0x0a, 0x07, 0x70, 0x6f, 0x6b, 0x65,
	0x6d, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x6f, 0x6b, 0x65,
	0x6d, 0x6f, 0x6e, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x49,
	0x64, 0x52, 0x07, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x12, 0x2d, 0x0a, 0x02, 0x49, 0x76,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e,
	0x5f, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x4d, 0x69, 0x6e, 0x4d, 0x61, 0x78,
	0x48, 0x00, 0x52, 0x02, 0x49, 0x76, 0x88, 0x01, 0x01, 0x12, 0x33, 0x0a, 0x05, 0x41, 0x74, 0x6b,
	0x49, 0x76, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x6d,
	0x6f, 0x6e, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x4d, 0x69, 0x6e, 0x4d,
	0x61, 0x78, 0x48, 0x01, 0x52, 0x05, 0x41, 0x74, 0x6b, 0x49, 0x76, 0x88, 0x01, 0x01, 0x12, 0x33,
	0x0a, 0x05, 0x44, 0x65, 0x66, 0x49, 0x76, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x61, 0x6e, 0x67,
	0x65, 0x4d, 0x69, 0x6e, 0x4d, 0x61, 0x78, 0x48, 0x02, 0x52, 0x05, 0x44, 0x65, 0x66, 0x49, 0x76,
	0x88, 0x01, 0x01, 0x12, 0x33, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x49, 0x76, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x5f, 0x61, 0x70, 0x69,
	0x2e, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x4d, 0x69, 0x6e, 0x4d, 0x61, 0x78, 0x48, 0x03, 0x52, 0x05,
	0x53, 0x74, 0x61, 0x49, 0x76, 0x88, 0x01, 0x01, 0x12, 0x33, 0x0a, 0x05, 0x4c, 0x65, 0x76, 0x65,
	0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f,
	0x6e, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x4d, 0x69, 0x6e, 0x4d, 0x61,
	0x78, 0x48, 0x04, 0x52, 0x05, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x88, 0x01, 0x01, 0x12, 0x2d, 0x0a,
	0x02, 0x43, 0x70, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x6f, 0x6b, 0x65,
	0x6d, 0x6f, 0x6e, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x4d, 0x69, 0x6e,
	0x4d, 0x61, 0x78, 0x48, 0x05, 0x52, 0x02, 0x43, 0x70, 0x88, 0x01, 0x01, 0x12, 0x35, 0x0a, 0x06,
	0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70,
	0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x61, 0x6e, 0x67, 0x65,
	0x4d, 0x69, 0x6e, 0x4d, 0x61, 0x78, 0x48, 0x06, 0x52, 0x06, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x88, 0x01, 0x01, 0x12, 0x31, 0x0a, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x5f, 0x61, 0x70, 0x69, 0x2e,
	0x52, 0x61, 0x6e, 0x67, 0x65, 0x4d, 0x69, 0x6e, 0x4d, 0x61, 0x78, 0x48, 0x07, 0x52, 0x04, 0x53,
	0x69, 0x7a, 0x65, 0x88, 0x01, 0x01, 0x12, 0x49, 0x0a, 0x10, 0x50, 0x76, 0x70, 0x4c, 0x69, 0x74,
	0x74, 0x6c, 0x65, 0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x18, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x52,
	0x61, 0x6e, 0x67, 0x65, 0x4d, 0x69, 0x6e, 0x4d, 0x61, 0x78, 0x48, 0x08, 0x52, 0x10, 0x50, 0x76,
	0x70, 0x4c, 0x69, 0x74, 0x74, 0x6c, 0x65, 0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x88, 0x01,
	0x01, 0x12, 0x47, 0x0a, 0x0f, 0x50, 0x76, 0x70, 0x47, 0x72, 0x65, 0x61, 0x74, 0x52, 0x61, 0x6e,
	0x6b, 0x69, 0x6e, 0x67, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x6f, 0x6b,
	0x65, 0x6d, 0x6f, 0x6e, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x4d, 0x69,
	0x6e, 0x4d, 0x61, 0x78, 0x48, 0x09, 0x52, 0x0f, 0x50, 0x76, 0x70, 0x47, 0x72, 0x65, 0x61, 0x74,
	0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x88, 0x01, 0x01, 0x12, 0x47, 0x0a, 0x0f, 0x50, 0x76,
	0x70, 0x55, 0x6c, 0x74, 0x72, 0x61, 0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x18, 0x0c, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x5f, 0x61, 0x70,
	0x69, 0x2e, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x4d, 0x69, 0x6e, 0x4d, 0x61, 0x78, 0x48, 0x0a, 0x52,
	0x0f, 0x50, 0x76, 0x70, 0x55, 0x6c, 0x74, 0x72, 0x61, 0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67,
	0x88, 0x01, 0x01, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x49, 0x76, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x41,
	0x74, 0x6b, 0x49, 0x76, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x44, 0x65, 0x66, 0x49, 0x76, 0x42, 0x08,
	0x0a, 0x06, 0x5f, 0x53, 0x74, 0x61, 0x49, 0x76, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x4c, 0x65, 0x76,
	0x65, 0x6c, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x43, 0x70, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x47, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x53, 0x69, 0x7a, 0x65, 0x42, 0x13, 0x0a,
	0x11, 0x5f, 0x50, 0x76, 0x70, 0x4c, 0x69, 0x74, 0x74, 0x6c, 0x65, 0x52, 0x61, 0x6e, 0x6b, 0x69,
	0x6e, 0x67, 0x42, 0x12, 0x0a, 0x10, 0x5f, 0x50, 0x76, 0x70, 0x47, 0x72, 0x65, 0x61, 0x74, 0x52,
	0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x42, 0x12, 0x0a, 0x10, 0x5f, 0x50, 0x76, 0x70, 0x55, 0x6c,
	0x74, 0x72, 0x61, 0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x22, 0x49, 0x0a, 0x09, 0x50, 0x6f,
	0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x13, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x02, 0x69, 0x64, 0x88, 0x01, 0x01, 0x12, 0x17, 0x0a, 0x04,
	0x66, 0x6f, 0x72, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x48, 0x01, 0x52, 0x04, 0x66, 0x6f,
	0x72, 0x6d, 0x88, 0x01, 0x01, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x69, 0x64, 0x42, 0x07, 0x0a, 0x05,
	0x5f, 0x66, 0x6f, 0x72, 0x6d, 0x22, 0x4b, 0x0a, 0x0b, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x4d, 0x69,
	0x6e, 0x4d, 0x61, 0x78, 0x12, 0x15, 0x0a, 0x03, 0x6d, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x48, 0x00, 0x52, 0x03, 0x6d, 0x69, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x15, 0x0a, 0x03, 0x6d,
	0x61, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x48, 0x01, 0x52, 0x03, 0x6d, 0x61, 0x78, 0x88,
	0x01, 0x01, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x6d, 0x69, 0x6e, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x6d,
	0x61, 0x78, 0x22, 0xb0, 0x01, 0x0a, 0x13, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x53, 0x63,
	0x61, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x27, 0x2e, 0x70, 0x6f, 0x6b,
	0x65, 0x6d, 0x6f, 0x6e, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e,
	0x53, 0x63, 0x61, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x35, 0x0a, 0x07, 0x70,
	0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70,
	0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x6f, 0x6b, 0x65, 0x6d,
	0x6f, 0x6e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x07, 0x70, 0x6f, 0x6b, 0x65, 0x6d,
	0x6f, 0x6e, 0x22, 0x21, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x09, 0x0a, 0x05,
	0x55, 0x4e, 0x53, 0x45, 0x54, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45,
	0x53, 0x53, 0x10, 0xc8, 0x01, 0x22, 0xfc, 0x0c, 0x0a, 0x0e, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f,
	0x6e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x24, 0x0a, 0x0b, 0x70, 0x6f, 0x6b, 0x65,
	0x73, 0x74, 0x6f, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x0a, 0x70, 0x6f, 0x6b, 0x65, 0x73, 0x74, 0x6f, 0x70, 0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x1e,
	0x0a, 0x08, 0x73, 0x70, 0x61, 0x77, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x48, 0x01, 0x52, 0x07, 0x73, 0x70, 0x61, 0x77, 0x6e, 0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x10,
	0x0a, 0x03, 0x6c, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6c, 0x61, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6c,
	0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x02, 0x48, 0x02, 0x52, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x88, 0x01, 0x01, 0x12,
	0x17, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x48, 0x03, 0x52,
	0x04, 0x73, 0x69, 0x7a, 0x65, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x02, 0x48, 0x04, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x88, 0x01, 0x01, 0x12, 0x2e, 0x0a, 0x10, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x5f,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x48,
	0x05, 0x52, 0x0f, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x88, 0x01, 0x01, 0x12, 0x1d, 0x0a, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x48, 0x06, 0x52, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x88, 0x01, 0x01, 0x12, 0x22, 0x0a, 0x0a, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x5f,
	0x69, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x48, 0x07, 0x52, 0x09, 0x70, 0x6f, 0x6b, 0x65,
	0x6d, 0x6f, 0x6e, 0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x1a, 0x0a, 0x06, 0x6d, 0x6f, 0x76, 0x65,
	0x5f, 0x31, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x05, 0x48, 0x08, 0x52, 0x05, 0x6d, 0x6f, 0x76, 0x65,
	0x31, 0x88, 0x01, 0x01, 0x12, 0x1a, 0x0a, 0x06, 0x6d, 0x6f, 0x76, 0x65, 0x5f, 0x32, 0x18, 0x0d,
	0x20, 0x01, 0x28, 0x05, 0x48, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x76, 0x65, 0x32, 0x88, 0x01, 0x01,
	0x12, 0x1b, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x05,
	0x48, 0x0a, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x88, 0x01, 0x01, 0x12, 0x13, 0x0a,
	0x02, 0x63, 0x70, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x05, 0x48, 0x0b, 0x52, 0x02, 0x63, 0x70, 0x88,
	0x01, 0x01, 0x12, 0x1a, 0x0a, 0x06, 0x61, 0x74, 0x6b, 0x5f, 0x69, 0x76, 0x18, 0x10, 0x20, 0x01,
	0x28, 0x05, 0x48, 0x0c, 0x52, 0x05, 0x61, 0x74, 0x6b, 0x49, 0x76, 0x88, 0x01, 0x01, 0x12, 0x1a,
	0x0a, 0x06, 0x64, 0x65, 0x66, 0x5f, 0x69, 0x76, 0x18, 0x11, 0x20, 0x01, 0x28, 0x05, 0x48, 0x0d,
	0x52, 0x05, 0x64, 0x65, 0x66, 0x49, 0x76, 0x88, 0x01, 0x01, 0x12, 0x1a, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x5f, 0x69, 0x76, 0x18, 0x12, 0x20, 0x01, 0x28, 0x05, 0x48, 0x0e, 0x52, 0x05, 0x73, 0x74,
	0x61, 0x49, 0x76, 0x88, 0x01, 0x01, 0x12, 0x13, 0x0a, 0x02, 0x69, 0x76, 0x18, 0x13, 0x20, 0x01,
	0x28, 0x02, 0x48, 0x0f, 0x52, 0x02, 0x69, 0x76, 0x88, 0x01, 0x01, 0x12, 0x17, 0x0a, 0x04, 0x66,
	0x6f, 0x72, 0x6d, 0x18, 0x14, 0x20, 0x01, 0x28, 0x05, 0x48, 0x10, 0x52, 0x04, 0x66, 0x6f, 0x72,
	0x6d, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x15, 0x20,
	0x01, 0x28, 0x05, 0x48, 0x11, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x88, 0x01, 0x01, 0x12,
	0x30, 0x0a, 0x11, 0x65, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x5f, 0x77, 0x65, 0x61,
	0x74, 0x68, 0x65, 0x72, 0x18, 0x16, 0x20, 0x01, 0x28, 0x05, 0x48, 0x12, 0x52, 0x10, 0x65, 0x6e,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x88, 0x01,
	0x01, 0x12, 0x1d, 0x0a, 0x07, 0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x18, 0x17, 0x20, 0x01,
	0x28, 0x05, 0x48, 0x13, 0x52, 0x07, 0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x88, 0x01, 0x01,
	0x12, 0x1d, 0x0a, 0x07, 0x63, 0x6f, 0x73, 0x74, 0x75, 0x6d, 0x65, 0x18, 0x18, 0x20, 0x01, 0x28,
	0x05, 0x48, 0x14, 0x52, 0x07, 0x63, 0x6f, 0x73, 0x74, 0x75, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x12,
	0x35, 0x0a, 0x14, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x73, 0x65, 0x65, 0x6e, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x19, 0x20, 0x01, 0x28, 0x03, 0x48, 0x15, 0x52,
	0x12, 0x66, 0x69, 0x72, 0x73, 0x74, 0x53, 0x65, 0x65, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x88, 0x01, 0x01, 0x12, 0x1d, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x64, 0x18, 0x1a, 0x20, 0x01, 0x28, 0x05, 0x48, 0x16, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x64, 0x88, 0x01, 0x01, 0x12, 0x1c, 0x0a, 0x07, 0x63, 0x65, 0x6c, 0x6c, 0x5f, 0x69, 0x64,
	0x18, 0x1b, 0x20, 0x01, 0x28, 0x03, 0x48, 0x17, 0x52, 0x06, 0x63, 0x65, 0x6c, 0x6c, 0x49, 0x64,
	0x88, 0x01, 0x01, 0x12, 0x3a, 0x0a, 0x19, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x5f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64,
	0x18, 0x1c, 0x20, 0x01, 0x28, 0x08, 0x52, 0x17, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x12,
	0x31, 0x0a, 0x12, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x70, 0x6f, 0x6b, 0x65, 0x6d,
	0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x1d, 0x20, 0x01, 0x28, 0x05, 0x48, 0x18, 0x52, 0x10, 0x64,
	0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x49, 0x64, 0x88,
	0x01, 0x01, 0x12, 0x1e, 0x0a, 0x08, 0x69, 0x73, 0x5f, 0x64, 0x69, 0x74, 0x74, 0x6f, 0x18, 0x1e,
	0x20, 0x01, 0x28, 0x08, 0x48, 0x19, 0x52, 0x07, 0x69, 0x73, 0x44, 0x69, 0x74, 0x74, 0x6f, 0x88,
	0x01, 0x01, 0x12, 0x20, 0x0a, 0x09, 0x73, 0x65, 0x65, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x1f, 0x20, 0x01, 0x28, 0x09, 0x48, 0x1a, 0x52, 0x08, 0x73, 0x65, 0x65, 0x6e, 0x54, 0x79, 0x70,
	0x65, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x05, 0x73, 0x68, 0x69, 0x6e, 0x79, 0x18, 0x20, 0x20,
	0x01, 0x28, 0x08, 0x48, 0x1b, 0x52, 0x05, 0x73, 0x68, 0x69, 0x6e, 0x79, 0x88, 0x01, 0x01, 0x12,
	0x1f, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x21, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x1c, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x88, 0x01, 0x01,
	0x12, 0x20, 0x0a, 0x09, 0x63, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x5f, 0x31, 0x18, 0x22, 0x20,
	0x01, 0x28, 0x02, 0x48, 0x1d, 0x52, 0x08, 0x63, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x31, 0x88,
	0x01, 0x01, 0x12, 0x20, 0x0a, 0x09, 0x63, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x5f, 0x32, 0x18,
	0x23, 0x20, 0x01, 0x28, 0x02, 0x48, 0x1e, 0x52, 0x08, 0x63, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65,
	0x32, 0x88, 0x01, 0x01, 0x12, 0x20, 0x0a, 0x09, 0x63, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x5f,
	0x33, 0x18, 0x24, 0x20, 0x01, 0x28, 0x02, 0x48, 0x1f, 0x52, 0x08, 0x63, 0x61, 0x70, 0x74, 0x75,
	0x72, 0x65, 0x33, 0x88, 0x01, 0x01, 0x12, 0x15, 0x0a, 0x03, 0x70, 0x76, 0x70, 0x18, 0x25, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x20, 0x52, 0x03, 0x70, 0x76, 0x70, 0x88, 0x01, 0x01, 0x12, 0x1f, 0x0a,
	0x08, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x26, 0x20, 0x01, 0x28, 0x02, 0x48,
	0x21, 0x52, 0x08, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0e,
	0x0a, 0x0c, 0x5f, 0x70, 0x6f, 0x6b, 0x65, 0x73, 0x74, 0x6f, 0x70, 0x5f, 0x69, 0x64, 0x42, 0x0b,
	0x0a, 0x09, 0x5f, 0x73, 0x70, 0x61, 0x77, 0x6e, 0x5f, 0x69, 0x64, 0x42, 0x09, 0x0a, 0x07, 0x5f,
	0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x42,
	0x09, 0x0a, 0x07, 0x5f, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x42, 0x13, 0x0a, 0x11, 0x5f, 0x65,
	0x78, 0x70, 0x69, 0x72, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x42,
	0x0a, 0x0a, 0x08, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x42, 0x0d, 0x0a, 0x0b, 0x5f,
	0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x6d,
	0x6f, 0x76, 0x65, 0x5f, 0x31, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x6d, 0x6f, 0x76, 0x65, 0x5f, 0x32,
	0x42, 0x09, 0x0a, 0x07, 0x5f, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x42, 0x05, 0x0a, 0x03, 0x5f,
	0x63, 0x70, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x61, 0x74, 0x6b, 0x5f, 0x69, 0x76, 0x42, 0x09, 0x0a,
	0x07, 0x5f, 0x64, 0x65, 0x66, 0x5f, 0x69, 0x76, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x73, 0x74, 0x61,
	0x5f, 0x69, 0x76, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x69, 0x76, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x66,
	0x6f, 0x72, 0x6d, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x42, 0x14, 0x0a,
	0x12, 0x5f, 0x65, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x5f, 0x77, 0x65, 0x61, 0x74,
	0x68, 0x65, 0x72, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x42,
	0x0a, 0x0a, 0x08, 0x5f, 0x63, 0x6f, 0x73, 0x74, 0x75, 0x6d, 0x65, 0x42, 0x17, 0x0a, 0x15, 0x5f,
	0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x73, 0x65, 0x65, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64,
	0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x63, 0x65, 0x6c, 0x6c, 0x5f, 0x69, 0x64, 0x42, 0x15, 0x0a, 0x13,
	0x5f, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e,
	0x5f, 0x69, 0x64, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x69, 0x73, 0x5f, 0x64, 0x69, 0x74, 0x74, 0x6f,
	0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x73, 0x65, 0x65, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x42, 0x08,
	0x0a, 0x06, 0x5f, 0x73, 0x68, 0x69, 0x6e, 0x79, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x75, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x63, 0x61, 0x70, 0x74, 0x75, 0x72,
	0x65, 0x5f, 0x31, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x63, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x5f,
	0x32, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x63, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x5f, 0x33, 0x42,
	0x06, 0x0a, 0x04, 0x5f, 0x70, 0x76, 0x70, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x64, 0x69, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x32, 0x58, 0x0a, 0x07, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x12,
	0x4d, 0x0a, 0x06, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x1f, 0x2e, 0x70, 0x6f, 0x6b, 0x65,
	0x6d, 0x6f, 0x6e, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x53,
	0x63, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x70, 0x6f, 0x6b,
	0x65, 0x6d, 0x6f, 0x6e, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e,
	0x53, 0x63, 0x61, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x22,
	0x5a, 0x20, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x75, 0x6e, 0x6f,
	0x77, 0x6e, 0x68, 0x61, 0x73, 0x68, 0x2f, 0x67, 0x6f, 0x6c, 0x62, 0x61, 0x74, 0x2f, 0x67, 0x72,
	0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var file_grpc_pokemon_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_grpc_pokemon_api_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_grpc_pokemon_api_proto_goTypes = []any{
	(PokemonScanResponse_Status)(0), // 0: pokemon_api.PokemonScanResponse.Status
	(*PokemonScanRequest)(nil),      // 1: pokemon_api.PokemonScanRequest
	(*PokemonDnf)(nil),              // 2: pokemon_api.PokemonDnf
	(*PokemonId)(nil),               // 3: pokemon_api.PokemonId
	(*RangeMinMax)(nil),             // 4: pokemon_api.RangeMinMax
	(*PokemonScanResponse)(nil),     // 5: pokemon_api.PokemonScanResponse
	(*PokemonDetails)(nil),          // 6: pokemon_api.PokemonDetails
}
var file_grpc_pokemon_api_proto_depIdxs = []int32{
	2,  // 0: pokemon_api.PokemonScanRequest.filters:type_name -> pokemon_api.PokemonDnf
	3,  // 1: pokemon_api.PokemonDnf.pokemon:type_name -> pokemon_api.PokemonId
	4,  // 2: pokemon_api.PokemonDnf.Iv:type_name -> pokemon_api.RangeMinMax
	4,  // 3: pokemon_api.PokemonDnf.AtkIv:type_name -> pokemon_api.RangeMinMax
	4,  // 4: pokemon_api.PokemonDnf.DefIv:type_name -> pokemon_api.RangeMinMax
	4,  // 5: pokemon_api.PokemonDnf.StaIv:type_name -> pokemon_api.RangeMinMax
	4,  // 6: pokemon_api.PokemonDnf.Level:type_name -> pokemon_api.RangeMinMax
	4,  // 7: pokemon_api.PokemonDnf.Cp:type_name -> pokemon_api.RangeMinMax
	4,  // 8: pokemon_api.PokemonDnf.Gender:type_name -> pokemon_api.RangeMinMax
	4,  // 9: pokemon_api.PokemonDnf.Size:type_name -> pokemon_api.RangeMinMax
	4,  // 10: pokemon_api.PokemonDnf.PvpLittleRanking:type_name -> pokemon_api.RangeMinMax
	4,  // 11: pokemon_api.PokemonDnf.PvpGreatRanking:type_name -> pokemon_api.RangeMinMax
	4,  // 12: pokemon_api.PokemonDnf.PvpUltraRanking:type_name -> pokemon_api.RangeMinMax
	0,  // 13: pokemon_api.PokemonScanResponse.status:type_name -> pokemon_api.PokemonScanResponse.Status
	6,  // 14: pokemon_api.PokemonScanResponse.pokemon:type_name -> pokemon_api.PokemonDetails
	1,  // 15: pokemon_api.Pokemon.Search:input_type -> pokemon_api.PokemonScanRequest
	5,  // 16: pokemon_api.Pokemon.Search:output_type -> pokemon_api.PokemonScanResponse
	16, // [16:17] is the sub-list for method output_type
	15, // [15:16] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_grpc_pokemon_api_proto_init() }
func file_grpc_pokemon_api_proto_init() {
	if File_grpc_pokemon_api_proto != nil {
		return
	}
	file_grpc_pokemon_api_proto_msgTypes[1].OneofWrappers = []any{}
	file_grpc_pokemon_api_proto_msgTypes[2].OneofWrappers = []any{}
	file_grpc_pokemon_api_proto_msgTypes[3].OneofWrappers = []any{}
	file_grpc_pokemon_api_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_pokemon_api_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_pokemon_api_proto_goTypes,
		DependencyIndexes: file_grpc_pokemon_api_proto_depIdxs,
		EnumInfos:         file_grpc_pokemon_api_proto_enumTypes,
		MessageInfos:      file_grpc_pokemon_api_proto_msgTypes,
	}.Build()
	File_grpc_pokemon_api_proto = out.File
	file_grpc_pokemon_api_proto_rawDesc = nil
	file_grpc_pokemon_api_proto_goTypes = nil
	file_grpc_pokemon_api_proto_depIdxs = nil
}
