// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: grpc/pokemon_internal.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PokemonInternal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ScanHistory []*PokemonScan `protobuf:"bytes,1,rep,name=scan_history,json=scanHistory,proto3" json:"scan_history,omitempty"`
}

func (x *PokemonInternal) Reset() {
	*x = PokemonInternal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_pokemon_internal_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PokemonInternal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PokemonInternal) ProtoMessage() {}

func (x *PokemonInternal) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pokemon_internal_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PokemonInternal.ProtoReflect.Descriptor instead.
func (*PokemonInternal) Descriptor() ([]byte, []int) {
	return file_grpc_pokemon_internal_proto_rawDescGZIP(), []int{0}
}

func (x *PokemonInternal) GetScanHistory() []*PokemonScan {
	if x != nil {
		return x.ScanHistory
	}
	return nil
}

type PokemonScan struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// from display
	Weather int32 `protobuf:"varint,1,opt,name=weather,proto3" json:"weather,omitempty"`
	Strong  bool  `protobuf:"varint,2,opt,name=strong,proto3" json:"strong,omitempty"`
	// from encounter
	Level   int32 `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	Attack  int32 `protobuf:"varint,4,opt,name=attack,proto3" json:"attack,omitempty"`
	Defense int32 `protobuf:"varint,5,opt,name=defense,proto3" json:"defense,omitempty"`
	Stamina int32 `protobuf:"varint,6,opt,name=stamina,proto3" json:"stamina,omitempty"`
	// for Ditto detection
	CellWeather int32 `protobuf:"varint,7,opt,name=cell_weather,json=cellWeather,proto3" json:"cell_weather,omitempty"`
	Pokemon     int32 `protobuf:"varint,8,opt,name=pokemon,proto3" json:"pokemon,omitempty"`
	Costume     int32 `protobuf:"varint,9,opt,name=costume,proto3" json:"costume,omitempty"`
	Gender      int32 `protobuf:"varint,10,opt,name=gender,proto3" json:"gender,omitempty"`
	Form        int32 `protobuf:"varint,11,opt,name=form,proto3" json:"form,omitempty"`
	// this is set if there is only one non-strong IV set but we were able to confirm it for some reason
	Confirmed bool `protobuf:"varint,12,opt,name=confirmed,proto3" json:"confirmed,omitempty"`
}

func (x *PokemonScan) Reset() {
	*x = PokemonScan{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_pokemon_internal_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PokemonScan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PokemonScan) ProtoMessage() {}

func (x *PokemonScan) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pokemon_internal_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PokemonScan.ProtoReflect.Descriptor instead.
func (*PokemonScan) Descriptor() ([]byte, []int) {
	return file_grpc_pokemon_internal_proto_rawDescGZIP(), []int{1}
}

func (x *PokemonScan) GetWeather() int32 {
	if x != nil {
		return x.Weather
	}
	return 0
}

func (x *PokemonScan) GetStrong() bool {
	if x != nil {
		return x.Strong
	}
	return false
}

func (x *PokemonScan) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *PokemonScan) GetAttack() int32 {
	if x != nil {
		return x.Attack
	}
	return 0
}

func (x *PokemonScan) GetDefense() int32 {
	if x != nil {
		return x.Defense
	}
	return 0
}

func (x *PokemonScan) GetStamina() int32 {
	if x != nil {
		return x.Stamina
	}
	return 0
}

func (x *PokemonScan) GetCellWeather() int32 {
	if x != nil {
		return x.CellWeather
	}
	return 0
}

func (x *PokemonScan) GetPokemon() int32 {
	if x != nil {
		return x.Pokemon
	}
	return 0
}

func (x *PokemonScan) GetCostume() int32 {
	if x != nil {
		return x.Costume
	}
	return 0
}

func (x *PokemonScan) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *PokemonScan) GetForm() int32 {
	if x != nil {
		return x.Form
	}
	return 0
}

func (x *PokemonScan) GetConfirmed() bool {
	if x != nil {
		return x.Confirmed
	}
	return false
}

var File_grpc_pokemon_internal_proto protoreflect.FileDescriptor

var file_grpc_pokemon_internal_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x5f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x70,
	0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x22,
	0x53, 0x0a, 0x0f, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x12, 0x40, 0x0a, 0x0c, 0x73, 0x63, 0x61, 0x6e, 0x5f, 0x68, 0x69, 0x73, 0x74, 0x6f,
	0x72, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x6d,
	0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x50, 0x6f, 0x6b, 0x65,
	0x6d, 0x6f, 0x6e, 0x53, 0x63, 0x61, 0x6e, 0x52, 0x0b, 0x73, 0x63, 0x61, 0x6e, 0x48, 0x69, 0x73,
	0x74, 0x6f, 0x72, 0x79, 0x22, 0xc2, 0x02, 0x0a, 0x0b, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e,
	0x53, 0x63, 0x61, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x72, 0x6f, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06,
	0x73, 0x74, 0x72, 0x6f, 0x6e, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x16, 0x0a, 0x06,
	0x61, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x61, 0x74,
	0x74, 0x61, 0x63, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x66, 0x65, 0x6e, 0x73, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x64, 0x65, 0x66, 0x65, 0x6e, 0x73, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x74, 0x61, 0x6d, 0x69, 0x6e, 0x61, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x73, 0x74, 0x61, 0x6d, 0x69, 0x6e, 0x61, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x65, 0x6c, 0x6c,
	0x5f, 0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b,
	0x63, 0x65, 0x6c, 0x6c, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x70,
	0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x70, 0x6f,
	0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x73, 0x74, 0x75, 0x6d, 0x65,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x63, 0x6f, 0x73, 0x74, 0x75, 0x6d, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x6f, 0x72, 0x6d, 0x18,
	0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x1c, 0x0a, 0x09, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x65, 0x64, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x65, 0x64, 0x42, 0x22, 0x5a, 0x20, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x75, 0x6e, 0x6f, 0x77, 0x6e, 0x68, 0x61, 0x73,
	0x68, 0x2f, 0x67, 0x6f, 0x6c, 0x62, 0x61, 0x74, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_pokemon_internal_proto_rawDescOnce sync.Once
	file_grpc_pokemon_internal_proto_rawDescData = file_grpc_pokemon_internal_proto_rawDesc
)

func file_grpc_pokemon_internal_proto_rawDescGZIP() []byte {
	file_grpc_pokemon_internal_proto_rawDescOnce.Do(func() {
		file_grpc_pokemon_internal_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_pokemon_internal_proto_rawDescData)
	})
	return file_grpc_pokemon_internal_proto_rawDescData
}

var file_grpc_pokemon_internal_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpc_pokemon_internal_proto_goTypes = []interface{}{
	(*PokemonInternal)(nil), // 0: pokemon_internal.PokemonInternal
	(*PokemonScan)(nil),     // 1: pokemon_internal.PokemonScan
}
var file_grpc_pokemon_internal_proto_depIdxs = []int32{
	1, // 0: pokemon_internal.PokemonInternal.scan_history:type_name -> pokemon_internal.PokemonScan
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_grpc_pokemon_internal_proto_init() }
func file_grpc_pokemon_internal_proto_init() {
	if File_grpc_pokemon_internal_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_pokemon_internal_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PokemonInternal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_pokemon_internal_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PokemonScan); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_pokemon_internal_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_grpc_pokemon_internal_proto_goTypes,
		DependencyIndexes: file_grpc_pokemon_internal_proto_depIdxs,
		MessageInfos:      file_grpc_pokemon_internal_proto_msgTypes,
	}.Build()
	File_grpc_pokemon_internal_proto = out.File
	file_grpc_pokemon_internal_proto_rawDesc = nil
	file_grpc_pokemon_internal_proto_goTypes = nil
	file_grpc_pokemon_internal_proto_depIdxs = nil
}
