// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.1
// source: grpc/pokemon_api.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Pokemon_Search_FullMethodName = "/pokemon_api.Pokemon/Search"
)

// PokemonClient is the client API for Pokemon service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Interface exported by the server.
type PokemonClient interface {
	Search(ctx context.Context, in *PokemonScanRequest, opts ...grpc.CallOption) (*PokemonScanResponse, error)
}

type pokemonClient struct {
	cc grpc.ClientConnInterface
}

func NewPokemonClient(cc grpc.ClientConnInterface) PokemonClient {
	return &pokemonClient{cc}
}

func (c *pokemonClient) Search(ctx context.Context, in *PokemonScanRequest, opts ...grpc.CallOption) (*PokemonScanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PokemonScanResponse)
	err := c.cc.Invoke(ctx, Pokemon_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PokemonServer is the server API for Pokemon service.
// All implementations must embed UnimplementedPokemonServer
// for forward compatibility.
//
// Interface exported by the server.
type PokemonServer interface {
	Search(context.Context, *PokemonScanRequest) (*PokemonScanResponse, error)
	mustEmbedUnimplementedPokemonServer()
}

// UnimplementedPokemonServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPokemonServer struct{}

func (UnimplementedPokemonServer) Search(context.Context, *PokemonScanRequest) (*PokemonScanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedPokemonServer) mustEmbedUnimplementedPokemonServer() {}
func (UnimplementedPokemonServer) testEmbeddedByValue()                 {}

// UnsafePokemonServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PokemonServer will
// result in compilation errors.
type UnsafePokemonServer interface {
	mustEmbedUnimplementedPokemonServer()
}

func RegisterPokemonServer(s grpc.ServiceRegistrar, srv PokemonServer) {
	// If the following call pancis, it indicates UnimplementedPokemonServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Pokemon_ServiceDesc, srv)
}

func _Pokemon_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PokemonScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokemonServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pokemon_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokemonServer).Search(ctx, req.(*PokemonScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Pokemon_ServiceDesc is the grpc.ServiceDesc for Pokemon service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Pokemon_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pokemon_api.Pokemon",
	HandlerType: (*PokemonServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _Pokemon_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/pokemon_api.proto",
}
