// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        v6.33.1
// source: grpc/pokemon_internal.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PokemonInternal struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ScanHistory *[]*PokemonScan        `protobuf:"bytes,1,rep,name=scan_history,json=scanHistory,proto3" json:"scan_history,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PokemonInternal) Reset() {
	*x = PokemonInternal{}
	mi := &file_grpc_pokemon_internal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PokemonInternal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PokemonInternal) ProtoMessage() {}

func (x *PokemonInternal) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pokemon_internal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PokemonInternal) GetScanHistory() []*PokemonScan {
	if x != nil {
		if x.xxx_hidden_ScanHistory != nil {
			return *x.xxx_hidden_ScanHistory
		}
	}
	return nil
}

func (x *PokemonInternal) SetScanHistory(v []*PokemonScan) {
	x.xxx_hidden_ScanHistory = &v
}

type PokemonInternal_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ScanHistory []*PokemonScan
}

func (b0 PokemonInternal_builder) Build() *PokemonInternal {
	m0 := &PokemonInternal{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ScanHistory = &b.ScanHistory
	return m0
}

type PokemonScan struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Weather     int32                  `protobuf:"varint,1,opt,name=weather,proto3" json:"weather,omitempty"`
	xxx_hidden_Strong      bool                   `protobuf:"varint,2,opt,name=strong,proto3" json:"strong,omitempty"`
	xxx_hidden_Level       int32                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	xxx_hidden_Attack      int32                  `protobuf:"varint,4,opt,name=attack,proto3" json:"attack,omitempty"`
	xxx_hidden_Defense     int32                  `protobuf:"varint,5,opt,name=defense,proto3" json:"defense,omitempty"`
	xxx_hidden_Stamina     int32                  `protobuf:"varint,6,opt,name=stamina,proto3" json:"stamina,omitempty"`
	xxx_hidden_CellWeather int32                  `protobuf:"varint,7,opt,name=cell_weather,json=cellWeather,proto3" json:"cell_weather,omitempty"`
	xxx_hidden_Pokemon     int32                  `protobuf:"varint,8,opt,name=pokemon,proto3" json:"pokemon,omitempty"`
	xxx_hidden_Costume     int32                  `protobuf:"varint,9,opt,name=costume,proto3" json:"costume,omitempty"`
	xxx_hidden_Gender      int32                  `protobuf:"varint,10,opt,name=gender,proto3" json:"gender,omitempty"`
	xxx_hidden_Form        int32                  `protobuf:"varint,11,opt,name=form,proto3" json:"form,omitempty"`
	xxx_hidden_Confirmed   bool                   `protobuf:"varint,12,opt,name=confirmed,proto3" json:"confirmed,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PokemonScan) Reset() {
	*x = PokemonScan{}
	mi := &file_grpc_pokemon_internal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PokemonScan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PokemonScan) ProtoMessage() {}

func (x *PokemonScan) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pokemon_internal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PokemonScan) GetWeather() int32 {
	if x != nil {
		return x.xxx_hidden_Weather
	}
	return 0
}

func (x *PokemonScan) GetStrong() bool {
	if x != nil {
		return x.xxx_hidden_Strong
	}
	return false
}

func (x *PokemonScan) GetLevel() int32 {
	if x != nil {
		return x.xxx_hidden_Level
	}
	return 0
}

func (x *PokemonScan) GetAttack() int32 {
	if x != nil {
		return x.xxx_hidden_Attack
	}
	return 0
}

func (x *PokemonScan) GetDefense() int32 {
	if x != nil {
		return x.xxx_hidden_Defense
	}
	return 0
}

func (x *PokemonScan) GetStamina() int32 {
	if x != nil {
		return x.xxx_hidden_Stamina
	}
	return 0
}

func (x *PokemonScan) GetCellWeather() int32 {
	if x != nil {
		return x.xxx_hidden_CellWeather
	}
	return 0
}

func (x *PokemonScan) GetPokemon() int32 {
	if x != nil {
		return x.xxx_hidden_Pokemon
	}
	return 0
}

func (x *PokemonScan) GetCostume() int32 {
	if x != nil {
		return x.xxx_hidden_Costume
	}
	return 0
}

func (x *PokemonScan) GetGender() int32 {
	if x != nil {
		return x.xxx_hidden_Gender
	}
	return 0
}

func (x *PokemonScan) GetForm() int32 {
	if x != nil {
		return x.xxx_hidden_Form
	}
	return 0
}

func (x *PokemonScan) GetConfirmed() bool {
	if x != nil {
		return x.xxx_hidden_Confirmed
	}
	return false
}

func (x *PokemonScan) SetWeather(v int32) {
	x.xxx_hidden_Weather = v
}

func (x *PokemonScan) SetStrong(v bool) {
	x.xxx_hidden_Strong = v
}

func (x *PokemonScan) SetLevel(v int32) {
	x.xxx_hidden_Level = v
}

func (x *PokemonScan) SetAttack(v int32) {
	x.xxx_hidden_Attack = v
}

func (x *PokemonScan) SetDefense(v int32) {
	x.xxx_hidden_Defense = v
}

func (x *PokemonScan) SetStamina(v int32) {
	x.xxx_hidden_Stamina = v
}

func (x *PokemonScan) SetCellWeather(v int32) {
	x.xxx_hidden_CellWeather = v
}

func (x *PokemonScan) SetPokemon(v int32) {
	x.xxx_hidden_Pokemon = v
}

func (x *PokemonScan) SetCostume(v int32) {
	x.xxx_hidden_Costume = v
}

func (x *PokemonScan) SetGender(v int32) {
	x.xxx_hidden_Gender = v
}

func (x *PokemonScan) SetForm(v int32) {
	x.xxx_hidden_Form = v
}

func (x *PokemonScan) SetConfirmed(v bool) {
	x.xxx_hidden_Confirmed = v
}

type PokemonScan_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// from display
	Weather int32
	Strong  bool
	// from encounter
	Level   int32
	Attack  int32
	Defense int32
	Stamina int32
	// for Ditto detection
	CellWeather int32
	Pokemon     int32
	Costume     int32
	Gender      int32
	Form        int32
	// this is set if there is only one non-strong IV set but we were able to confirm it for some reason
	Confirmed bool
}

func (b0 PokemonScan_builder) Build() *PokemonScan {
	m0 := &PokemonScan{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Weather = b.Weather
	x.xxx_hidden_Strong = b.Strong
	x.xxx_hidden_Level = b.Level
	x.xxx_hidden_Attack = b.Attack
	x.xxx_hidden_Defense = b.Defense
	x.xxx_hidden_Stamina = b.Stamina
	x.xxx_hidden_CellWeather = b.CellWeather
	x.xxx_hidden_Pokemon = b.Pokemon
	x.xxx_hidden_Costume = b.Costume
	x.xxx_hidden_Gender = b.Gender
	x.xxx_hidden_Form = b.Form
	x.xxx_hidden_Confirmed = b.Confirmed
	return m0
}

var File_grpc_pokemon_internal_proto protoreflect.FileDescriptor

var file_grpc_pokemon_internal_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x5f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x70,
	0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x22,
	0x53, 0x0a, 0x0f, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x12, 0x40, 0x0a, 0x0c, 0x73, 0x63, 0x61, 0x6e, 0x5f, 0x68, 0x69, 0x73, 0x74, 0x6f,
	0x72, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x6d,
	0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x50, 0x6f, 0x6b, 0x65,
	0x6d, 0x6f, 0x6e, 0x53, 0x63, 0x61, 0x6e, 0x52, 0x0b, 0x73, 0x63, 0x61, 0x6e, 0x48, 0x69, 0x73,
	0x74, 0x6f, 0x72, 0x79, 0x22, 0xc2, 0x02, 0x0a, 0x0b, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e,
	0x53, 0x63, 0x61, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x72, 0x6f, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06,
	0x73, 0x74, 0x72, 0x6f, 0x6e, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x16, 0x0a, 0x06,
	0x61, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x61, 0x74,
	0x74, 0x61, 0x63, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x66, 0x65, 0x6e, 0x73, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x64, 0x65, 0x66, 0x65, 0x6e, 0x73, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x74, 0x61, 0x6d, 0x69, 0x6e, 0x61, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x73, 0x74, 0x61, 0x6d, 0x69, 0x6e, 0x61, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x65, 0x6c, 0x6c,
	0x5f, 0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b,
	0x63, 0x65, 0x6c, 0x6c, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x70,
	0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x70, 0x6f,
	0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x73, 0x74, 0x75, 0x6d, 0x65,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x63, 0x6f, 0x73, 0x74, 0x75, 0x6d, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x6f, 0x72, 0x6d, 0x18,
	0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x1c, 0x0a, 0x09, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x65, 0x64, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x65, 0x64, 0x42, 0x22, 0x5a, 0x20, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x75, 0x6e, 0x6f, 0x77, 0x6e, 0x68, 0x61, 0x73,
	0x68, 0x2f, 0x67, 0x6f, 0x6c, 0x62, 0x61, 0x74, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var file_grpc_pokemon_internal_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpc_pokemon_internal_proto_goTypes = []any{
	(*PokemonInternal)(nil), // 0: pokemon_internal.PokemonInternal
	(*PokemonScan)(nil),     // 1: pokemon_internal.PokemonScan
}
var file_grpc_pokemon_internal_proto_depIdxs = []int32{
	1, // 0: pokemon_internal.PokemonInternal.scan_history:type_name -> pokemon_internal.PokemonScan
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_grpc_pokemon_internal_proto_init() }
func file_grpc_pokemon_internal_proto_init() {
	if File_grpc_pokemon_internal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_pokemon_internal_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_grpc_pokemon_internal_proto_goTypes,
		DependencyIndexes: file_grpc_pokemon_internal_proto_depIdxs,
		MessageInfos:      file_grpc_pokemon_internal_proto_msgTypes,
	}.Build()
	File_grpc_pokemon_internal_proto = out.File
	file_grpc_pokemon_internal_proto_rawDesc = nil
	file_grpc_pokemon_internal_proto_goTypes = nil
	file_grpc_pokemon_internal_proto_depIdxs = nil
}
