// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: grpc/pokemon_api.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PokemonScanResponse_Status int32

const (
	PokemonScanResponse_UNSET   PokemonScanResponse_Status = 0
	PokemonScanResponse_SUCCESS PokemonScanResponse_Status = 200
)

// Enum value maps for PokemonScanResponse_Status.
var (
	PokemonScanResponse_Status_name = map[int32]string{
		0:   "UNSET",
		200: "SUCCESS",
	}
	PokemonScanResponse_Status_value = map[string]int32{
		"UNSET":   0,
		"SUCCESS": 200,
	}
)

func (x PokemonScanResponse_Status) Enum() *PokemonScanResponse_Status {
	p := new(PokemonScanResponse_Status)
	*p = x
	return p
}

func (x PokemonScanResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PokemonScanResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_pokemon_api_proto_enumTypes[0].Descriptor()
}

func (PokemonScanResponse_Status) Type() protoreflect.EnumType {
	return &file_grpc_pokemon_api_proto_enumTypes[0]
}

func (x PokemonScanResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PokemonScanResponse_Status.Descriptor instead.
func (PokemonScanResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_grpc_pokemon_api_proto_rawDescGZIP(), []int{6, 0}
}

type PokemonScanResponseV3_Status int32

const (
	PokemonScanResponseV3_UNSET   PokemonScanResponseV3_Status = 0
	PokemonScanResponseV3_SUCCESS PokemonScanResponseV3_Status = 200
)

// Enum value maps for PokemonScanResponseV3_Status.
var (
	PokemonScanResponseV3_Status_name = map[int32]string{
		0:   "UNSET",
		200: "SUCCESS",
	}
	PokemonScanResponseV3_Status_value = map[string]int32{
		"UNSET":   0,
		"SUCCESS": 200,
	}
)

func (x PokemonScanResponseV3_Status) Enum() *PokemonScanResponseV3_Status {
	p := new(PokemonScanResponseV3_Status)
	*p = x
	return p
}

func (x PokemonScanResponseV3_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PokemonScanResponseV3_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_pokemon_api_proto_enumTypes[1].Descriptor()
}

func (PokemonScanResponseV3_Status) Type() protoreflect.EnumType {
	return &file_grpc_pokemon_api_proto_enumTypes[1]
}

func (x PokemonScanResponseV3_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PokemonScanResponseV3_Status.Descriptor instead.
func (PokemonScanResponseV3_Status) EnumDescriptor() ([]byte, []int) {
	return file_grpc_pokemon_api_proto_rawDescGZIP(), []int{7, 0}
}

type PokemonScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinLat        float32                `protobuf:"fixed32,1,opt,name=min_lat,json=minLat,proto3" json:"min_lat,omitempty"`
	MinLon        float32                `protobuf:"fixed32,2,opt,name=min_lon,json=minLon,proto3" json:"min_lon,omitempty"`
	MaxLat        float32                `protobuf:"fixed32,3,opt,name=max_lat,json=maxLat,proto3" json:"max_lat,omitempty"`
	MaxLon        float32                `protobuf:"fixed32,4,opt,name=max_lon,json=maxLon,proto3" json:"max_lon,omitempty"`
	Limit         int32                  `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	Filters       []*PokemonDnf          `protobuf:"bytes,7,rep,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PokemonScanRequest) Reset() {
	*x = PokemonScanRequest{}
	mi := &file_grpc_pokemon_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PokemonScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PokemonScanRequest) ProtoMessage() {}

func (x *PokemonScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pokemon_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PokemonScanRequest.ProtoReflect.Descriptor instead.
func (*PokemonScanRequest) Descriptor() ([]byte, []int) {
	return file_grpc_pokemon_api_proto_rawDescGZIP(), []int{0}
}

func (x *PokemonScanRequest) GetMinLat() float32 {
	if x != nil {
		return x.MinLat
	}
	return 0
}

func (x *PokemonScanRequest) GetMinLon() float32 {
	if x != nil {
		return x.MinLon
	}
	return 0
}

func (x *PokemonScanRequest) GetMaxLat() float32 {
	if x != nil {
		return x.MaxLat
	}
	return 0
}

func (x *PokemonScanRequest) GetMaxLon() float32 {
	if x != nil {
		return x.MaxLon
	}
	return 0
}

func (x *PokemonScanRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *PokemonScanRequest) GetFilters() []*PokemonDnf {
	if x != nil {
		return x.Filters
	}
	return nil
}

type PokemonScanRequestV3 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinLat        float32                `protobuf:"fixed32,1,opt,name=min_lat,json=minLat,proto3" json:"min_lat,omitempty"`
	MinLon        float32                `protobuf:"fixed32,2,opt,name=min_lon,json=minLon,proto3" json:"min_lon,omitempty"`
	MaxLat        float32                `protobuf:"fixed32,3,opt,name=max_lat,json=maxLat,proto3" json:"max_lat,omitempty"`
	MaxLon        float32                `protobuf:"fixed32,4,opt,name=max_lon,json=maxLon,proto3" json:"max_lon,omitempty"`
	Limit         int32                  `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	Filters       []*PokemonDnfV3        `protobuf:"bytes,7,rep,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PokemonScanRequestV3) Reset() {
	*x = PokemonScanRequestV3{}
	mi := &file_grpc_pokemon_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PokemonScanRequestV3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PokemonScanRequestV3) ProtoMessage() {}

func (x *PokemonScanRequestV3) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pokemon_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PokemonScanRequestV3.ProtoReflect.Descriptor instead.
func (*PokemonScanRequestV3) Descriptor() ([]byte, []int) {
	return file_grpc_pokemon_api_proto_rawDescGZIP(), []int{1}
}

func (x *PokemonScanRequestV3) GetMinLat() float32 {
	if x != nil {
		return x.MinLat
	}
	return 0
}

func (x *PokemonScanRequestV3) GetMinLon() float32 {
	if x != nil {
		return x.MinLon
	}
	return 0
}

func (x *PokemonScanRequestV3) GetMaxLat() float32 {
	if x != nil {
		return x.MaxLat
	}
	return 0
}

func (x *PokemonScanRequestV3) GetMaxLon() float32 {
	if x != nil {
		return x.MaxLon
	}
	return 0
}

func (x *PokemonScanRequestV3) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *PokemonScanRequestV3) GetFilters() []*PokemonDnfV3 {
	if x != nil {
		return x.Filters
	}
	return nil
}

type PokemonDnf struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Pokemon          []*PokemonId           `protobuf:"bytes,1,rep,name=pokemon,proto3" json:"pokemon,omitempty"`
	Iv               *RangeMinMax           `protobuf:"bytes,2,opt,name=Iv,proto3,oneof" json:"Iv,omitempty"`
	AtkIv            *RangeMinMax           `protobuf:"bytes,3,opt,name=AtkIv,proto3,oneof" json:"AtkIv,omitempty"`
	DefIv            *RangeMinMax           `protobuf:"bytes,4,opt,name=DefIv,proto3,oneof" json:"DefIv,omitempty"`
	StaIv            *RangeMinMax           `protobuf:"bytes,5,opt,name=StaIv,proto3,oneof" json:"StaIv,omitempty"`
	Level            *RangeMinMax           `protobuf:"bytes,6,opt,name=Level,proto3,oneof" json:"Level,omitempty"`
	Cp               *RangeMinMax           `protobuf:"bytes,7,opt,name=Cp,proto3,oneof" json:"Cp,omitempty"`
	Gender           *RangeMinMax           `protobuf:"bytes,8,opt,name=Gender,proto3,oneof" json:"Gender,omitempty"`
	Size             *RangeMinMax           `protobuf:"bytes,9,opt,name=Size,proto3,oneof" json:"Size,omitempty"`
	PvpLittleRanking *RangeMinMax           `protobuf:"bytes,10,opt,name=PvpLittleRanking,proto3,oneof" json:"PvpLittleRanking,omitempty"`
	PvpGreatRanking  *RangeMinMax           `protobuf:"bytes,11,opt,name=PvpGreatRanking,proto3,oneof" json:"PvpGreatRanking,omitempty"`
	PvpUltraRanking  *RangeMinMax           `protobuf:"bytes,12,opt,name=PvpUltraRanking,proto3,oneof" json:"PvpUltraRanking,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PokemonDnf) Reset() {
	*x = PokemonDnf{}
	mi := &file_grpc_pokemon_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PokemonDnf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PokemonDnf) ProtoMessage() {}

func (x *PokemonDnf) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pokemon_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PokemonDnf.ProtoReflect.Descriptor instead.
func (*PokemonDnf) Descriptor() ([]byte, []int) {
	return file_grpc_pokemon_api_proto_rawDescGZIP(), []int{2}
}

func (x *PokemonDnf) GetPokemon() []*PokemonId {
	if x != nil {
		return x.Pokemon
	}
	return nil
}

func (x *PokemonDnf) GetIv() *RangeMinMax {
	if x != nil {
		return x.Iv
	}
	return nil
}

func (x *PokemonDnf) GetAtkIv() *RangeMinMax {
	if x != nil {
		return x.AtkIv
	}
	return nil
}

func (x *PokemonDnf) GetDefIv() *RangeMinMax {
	if x != nil {
		return x.DefIv
	}
	return nil
}

func (x *PokemonDnf) GetStaIv() *RangeMinMax {
	if x != nil {
		return x.StaIv
	}
	return nil
}

func (x *PokemonDnf) GetLevel() *RangeMinMax {
	if x != nil {
		return x.Level
	}
	return nil
}

func (x *PokemonDnf) GetCp() *RangeMinMax {
	if x != nil {
		return x.Cp
	}
	return nil
}

func (x *PokemonDnf) GetGender() *RangeMinMax {
	if x != nil {
		return x.Gender
	}
	return nil
}

func (x *PokemonDnf) GetSize() *RangeMinMax {
	if x != nil {
		return x.Size
	}
	return nil
}

func (x *PokemonDnf) GetPvpLittleRanking() *RangeMinMax {
	if x != nil {
		return x.PvpLittleRanking
	}
	return nil
}

func (x *PokemonDnf) GetPvpGreatRanking() *RangeMinMax {
	if x != nil {
		return x.PvpGreatRanking
	}
	return nil
}

func (x *PokemonDnf) GetPvpUltraRanking() *RangeMinMax {
	if x != nil {
		return x.PvpUltraRanking
	}
	return nil
}

type PokemonDnfV3 struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Pokemon          []*PokemonId           `protobuf:"bytes,1,rep,name=pokemon,proto3" json:"pokemon,omitempty"`
	Iv               *RangeMinMax           `protobuf:"bytes,2,opt,name=Iv,proto3,oneof" json:"Iv,omitempty"`
	AtkIv            *RangeMinMax           `protobuf:"bytes,3,opt,name=AtkIv,proto3,oneof" json:"AtkIv,omitempty"`
	DefIv            *RangeMinMax           `protobuf:"bytes,4,opt,name=DefIv,proto3,oneof" json:"DefIv,omitempty"`
	StaIv            *RangeMinMax           `protobuf:"bytes,5,opt,name=StaIv,proto3,oneof" json:"StaIv,omitempty"`
	Level            *RangeMinMax           `protobuf:"bytes,6,opt,name=Level,proto3,oneof" json:"Level,omitempty"`
	Cp               *RangeMinMax           `protobuf:"bytes,7,opt,name=Cp,proto3,oneof" json:"Cp,omitempty"`
	Gender           []int32                `protobuf:"varint,8,rep,packed,name=Gender,proto3" json:"Gender,omitempty"`
	Size             *RangeMinMax           `protobuf:"bytes,9,opt,name=Size,proto3,oneof" json:"Size,omitempty"`
	PvpLittleRanking *RangeMinMax           `protobuf:"bytes,10,opt,name=PvpLittleRanking,proto3,oneof" json:"PvpLittleRanking,omitempty"`
	PvpGreatRanking  *RangeMinMax           `protobuf:"bytes,11,opt,name=PvpGreatRanking,proto3,oneof" json:"PvpGreatRanking,omitempty"`
	PvpUltraRanking  *RangeMinMax           `protobuf:"bytes,12,opt,name=PvpUltraRanking,proto3,oneof" json:"PvpUltraRanking,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PokemonDnfV3) Reset() {
	*x = PokemonDnfV3{}
	mi := &file_grpc_pokemon_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PokemonDnfV3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PokemonDnfV3) ProtoMessage() {}

func (x *PokemonDnfV3) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pokemon_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PokemonDnfV3.ProtoReflect.Descriptor instead.
func (*PokemonDnfV3) Descriptor() ([]byte, []int) {
	return file_grpc_pokemon_api_proto_rawDescGZIP(), []int{3}
}

func (x *PokemonDnfV3) GetPokemon() []*PokemonId {
	if x != nil {
		return x.Pokemon
	}
	return nil
}

func (x *PokemonDnfV3) GetIv() *RangeMinMax {
	if x != nil {
		return x.Iv
	}
	return nil
}

func (x *PokemonDnfV3) GetAtkIv() *RangeMinMax {
	if x != nil {
		return x.AtkIv
	}
	return nil
}

func (x *PokemonDnfV3) GetDefIv() *RangeMinMax {
	if x != nil {
		return x.DefIv
	}
	return nil
}

func (x *PokemonDnfV3) GetStaIv() *RangeMinMax {
	if x != nil {
		return x.StaIv
	}
	return nil
}

func (x *PokemonDnfV3) GetLevel() *RangeMinMax {
	if x != nil {
		return x.Level
	}
	return nil
}

func (x *PokemonDnfV3) GetCp() *RangeMinMax {
	if x != nil {
		return x.Cp
	}
	return nil
}

func (x *PokemonDnfV3) GetGender() []int32 {
	if x != nil {
		return x.Gender
	}
	return nil
}

func (x *PokemonDnfV3) GetSize() *RangeMinMax {
	if x != nil {
		return x.Size
	}
	return nil
}

func (x *PokemonDnfV3) GetPvpLittleRanking() *RangeMinMax {
	if x != nil {
		return x.PvpLittleRanking
	}
	return nil
}

func (x *PokemonDnfV3) GetPvpGreatRanking() *RangeMinMax {
	if x != nil {
		return x.PvpGreatRanking
	}
	return nil
}

func (x *PokemonDnfV3) GetPvpUltraRanking() *RangeMinMax {
	if x != nil {
		return x.PvpUltraRanking
	}
	return nil
}

type PokemonId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *int32                 `protobuf:"varint,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Form          *int32                 `protobuf:"varint,2,opt,name=form,proto3,oneof" json:"form,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PokemonId) Reset() {
	*x = PokemonId{}
	mi := &file_grpc_pokemon_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PokemonId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PokemonId) ProtoMessage() {}

func (x *PokemonId) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pokemon_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PokemonId.ProtoReflect.Descriptor instead.
func (*PokemonId) Descriptor() ([]byte, []int) {
	return file_grpc_pokemon_api_proto_rawDescGZIP(), []int{4}
}

func (x *PokemonId) GetId() int32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *PokemonId) GetForm() int32 {
	if x != nil && x.Form != nil {
		return *x.Form
	}
	return 0
}

type RangeMinMax struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Min           *int32                 `protobuf:"varint,1,opt,name=min,proto3,oneof" json:"min,omitempty"`
	Max           *int32                 `protobuf:"varint,2,opt,name=max,proto3,oneof" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RangeMinMax) Reset() {
	*x = RangeMinMax{}
	mi := &file_grpc_pokemon_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeMinMax) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeMinMax) ProtoMessage() {}

func (x *RangeMinMax) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pokemon_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeMinMax.ProtoReflect.Descriptor instead.
func (*RangeMinMax) Descriptor() ([]byte, []int) {
	return file_grpc_pokemon_api_proto_rawDescGZIP(), []int{5}
}

func (x *RangeMinMax) GetMin() int32 {
	if x != nil && x.Min != nil {
		return *x.Min
	}
	return 0
}

func (x *RangeMinMax) GetMax() int32 {
	if x != nil && x.Max != nil {
		return *x.Max
	}
	return 0
}

type PokemonScanResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Status        PokemonScanResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=pokemon_api.PokemonScanResponse_Status" json:"status,omitempty"`
	Pokemon       []*PokemonDetails          `protobuf:"bytes,2,rep,name=pokemon,proto3" json:"pokemon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PokemonScanResponse) Reset() {
	*x = PokemonScanResponse{}
	mi := &file_grpc_pokemon_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PokemonScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PokemonScanResponse) ProtoMessage() {}

func (x *PokemonScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pokemon_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PokemonScanResponse.ProtoReflect.Descriptor instead.
func (*PokemonScanResponse) Descriptor() ([]byte, []int) {
	return file_grpc_pokemon_api_proto_rawDescGZIP(), []int{6}
}

func (x *PokemonScanResponse) GetStatus() PokemonScanResponse_Status {
	if x != nil {
		return x.Status
	}
	return PokemonScanResponse_UNSET
}

func (x *PokemonScanResponse) GetPokemon() []*PokemonDetails {
	if x != nil {
		return x.Pokemon
	}
	return nil
}

type PokemonScanResponseV3 struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Status        PokemonScanResponseV3_Status `protobuf:"varint,1,opt,name=status,proto3,enum=pokemon_api.PokemonScanResponseV3_Status" json:"status,omitempty"`
	Pokemon       []*PokemonDetails            `protobuf:"bytes,2,rep,name=pokemon,proto3" json:"pokemon,omitempty"`
	Examined      int32                        `protobuf:"varint,3,opt,name=examined,proto3" json:"examined,omitempty"`
	Skipped       int32                        `protobuf:"varint,4,opt,name=skipped,proto3" json:"skipped,omitempty"`
	Total         int32                        `protobuf:"varint,5,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PokemonScanResponseV3) Reset() {
	*x = PokemonScanResponseV3{}
	mi := &file_grpc_pokemon_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PokemonScanResponseV3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PokemonScanResponseV3) ProtoMessage() {}

func (x *PokemonScanResponseV3) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pokemon_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PokemonScanResponseV3.ProtoReflect.Descriptor instead.
func (*PokemonScanResponseV3) Descriptor() ([]byte, []int) {
	return file_grpc_pokemon_api_proto_rawDescGZIP(), []int{7}
}

func (x *PokemonScanResponseV3) GetStatus() PokemonScanResponseV3_Status {
	if x != nil {
		return x.Status
	}
	return PokemonScanResponseV3_UNSET
}

func (x *PokemonScanResponseV3) GetPokemon() []*PokemonDetails {
	if x != nil {
		return x.Pokemon
	}
	return nil
}

func (x *PokemonScanResponseV3) GetExamined() int32 {
	if x != nil {
		return x.Examined
	}
	return 0
}

func (x *PokemonScanResponseV3) GetSkipped() int32 {
	if x != nil {
		return x.Skipped
	}
	return 0
}

func (x *PokemonScanResponseV3) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type PokemonDetails struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Id                      uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PokestopId              *string                `protobuf:"bytes,2,opt,name=pokestop_id,json=pokestopId,proto3,oneof" json:"pokestop_id,omitempty"`
	SpawnId                 *int64                 `protobuf:"varint,3,opt,name=spawn_id,json=spawnId,proto3,oneof" json:"spawn_id,omitempty"`
	Lat                     float64                `protobuf:"fixed64,4,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon                     float64                `protobuf:"fixed64,5,opt,name=lon,proto3" json:"lon,omitempty"`
	Weight                  *float32               `protobuf:"fixed32,6,opt,name=weight,proto3,oneof" json:"weight,omitempty"`
	Size                    *int32                 `protobuf:"varint,7,opt,name=size,proto3,oneof" json:"size,omitempty"`
	Height                  *float32               `protobuf:"fixed32,8,opt,name=height,proto3,oneof" json:"height,omitempty"`
	ExpireTimestamp         *int32                 `protobuf:"varint,9,opt,name=expire_timestamp,json=expireTimestamp,proto3,oneof" json:"expire_timestamp,omitempty"`
	Updated                 *int32                 `protobuf:"varint,10,opt,name=updated,proto3,oneof" json:"updated,omitempty"`
	PokemonId               *int32                 `protobuf:"varint,11,opt,name=pokemon_id,json=pokemonId,proto3,oneof" json:"pokemon_id,omitempty"`
	Move_1                  *int32                 `protobuf:"varint,12,opt,name=move_1,json=move1,proto3,oneof" json:"move_1,omitempty"`
	Move_2                  *int32                 `protobuf:"varint,13,opt,name=move_2,json=move2,proto3,oneof" json:"move_2,omitempty"`
	Gender                  *int32                 `protobuf:"varint,14,opt,name=gender,proto3,oneof" json:"gender,omitempty"`
	Cp                      *int32                 `protobuf:"varint,15,opt,name=cp,proto3,oneof" json:"cp,omitempty"`
	AtkIv                   *int32                 `protobuf:"varint,16,opt,name=atk_iv,json=atkIv,proto3,oneof" json:"atk_iv,omitempty"`
	DefIv                   *int32                 `protobuf:"varint,17,opt,name=def_iv,json=defIv,proto3,oneof" json:"def_iv,omitempty"`
	StaIv                   *int32                 `protobuf:"varint,18,opt,name=sta_iv,json=staIv,proto3,oneof" json:"sta_iv,omitempty"`
	Iv                      *float32               `protobuf:"fixed32,19,opt,name=iv,proto3,oneof" json:"iv,omitempty"`
	Form                    *int32                 `protobuf:"varint,20,opt,name=form,proto3,oneof" json:"form,omitempty"`
	Level                   *int32                 `protobuf:"varint,21,opt,name=level,proto3,oneof" json:"level,omitempty"`
	EncounterWeather        *int32                 `protobuf:"varint,22,opt,name=encounter_weather,json=encounterWeather,proto3,oneof" json:"encounter_weather,omitempty"`
	Weather                 *int32                 `protobuf:"varint,23,opt,name=weather,proto3,oneof" json:"weather,omitempty"`
	Costume                 *int32                 `protobuf:"varint,24,opt,name=costume,proto3,oneof" json:"costume,omitempty"`
	FirstSeenTimestamp      *int64                 `protobuf:"varint,25,opt,name=first_seen_timestamp,json=firstSeenTimestamp,proto3,oneof" json:"first_seen_timestamp,omitempty"`
	Changed                 *int32                 `protobuf:"varint,26,opt,name=changed,proto3,oneof" json:"changed,omitempty"`
	CellId                  *int64                 `protobuf:"varint,27,opt,name=cell_id,json=cellId,proto3,oneof" json:"cell_id,omitempty"`
	ExpireTimestampVerified bool                   `protobuf:"varint,28,opt,name=expire_timestamp_verified,json=expireTimestampVerified,proto3" json:"expire_timestamp_verified,omitempty"`
	DisplayPokemonId        *int32                 `protobuf:"varint,29,opt,name=display_pokemon_id,json=displayPokemonId,proto3,oneof" json:"display_pokemon_id,omitempty"`
	IsDitto                 *bool                  `protobuf:"varint,30,opt,name=is_ditto,json=isDitto,proto3,oneof" json:"is_ditto,omitempty"`
	SeenType                *string                `protobuf:"bytes,31,opt,name=seen_type,json=seenType,proto3,oneof" json:"seen_type,omitempty"`
	Shiny                   *bool                  `protobuf:"varint,32,opt,name=shiny,proto3,oneof" json:"shiny,omitempty"`
	Username                *string                `protobuf:"bytes,33,opt,name=username,proto3,oneof" json:"username,omitempty"`
	Capture_1               *float32               `protobuf:"fixed32,34,opt,name=capture_1,json=capture1,proto3,oneof" json:"capture_1,omitempty"`
	Capture_2               *float32               `protobuf:"fixed32,35,opt,name=capture_2,json=capture2,proto3,oneof" json:"capture_2,omitempty"`
	Capture_3               *float32               `protobuf:"fixed32,36,opt,name=capture_3,json=capture3,proto3,oneof" json:"capture_3,omitempty"`
	Pvp                     *string                `protobuf:"bytes,37,opt,name=pvp,proto3,oneof" json:"pvp,omitempty"`
	Distance                *float32               `protobuf:"fixed32,38,opt,name=distance,proto3,oneof" json:"distance,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *PokemonDetails) Reset() {
	*x = PokemonDetails{}
	mi := &file_grpc_pokemon_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PokemonDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PokemonDetails) ProtoMessage() {}

func (x *PokemonDetails) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pokemon_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PokemonDetails.ProtoReflect.Descriptor instead.
func (*PokemonDetails) Descriptor() ([]byte, []int) {
	return file_grpc_pokemon_api_proto_rawDescGZIP(), []int{8}
}

func (x *PokemonDetails) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PokemonDetails) GetPokestopId() string {
	if x != nil && x.PokestopId != nil {
		return *x.PokestopId
	}
	return ""
}

func (x *PokemonDetails) GetSpawnId() int64 {
	if x != nil && x.SpawnId != nil {
		return *x.SpawnId
	}
	return 0
}

func (x *PokemonDetails) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *PokemonDetails) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *PokemonDetails) GetWeight() float32 {
	if x != nil && x.Weight != nil {
		return *x.Weight
	}
	return 0
}

func (x *PokemonDetails) GetSize() int32 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

func (x *PokemonDetails) GetHeight() float32 {
	if x != nil && x.Height != nil {
		return *x.Height
	}
	return 0
}

func (x *PokemonDetails) GetExpireTimestamp() int32 {
	if x != nil && x.ExpireTimestamp != nil {
		return *x.ExpireTimestamp
	}
	return 0
}

func (x *PokemonDetails) GetUpdated() int32 {
	if x != nil && x.Updated != nil {
		return *x.Updated
	}
	return 0
}

func (x *PokemonDetails) GetPokemonId() int32 {
	if x != nil && x.PokemonId != nil {
		return *x.PokemonId
	}
	return 0
}

func (x *PokemonDetails) GetMove_1() int32 {
	if x != nil && x.Move_1 != nil {
		return *x.Move_1
	}
	return 0
}

func (x *PokemonDetails) GetMove_2() int32 {
	if x != nil && x.Move_2 != nil {
		return *x.Move_2
	}
	return 0
}

func (x *PokemonDetails) GetGender() int32 {
	if x != nil && x.Gender != nil {
		return *x.Gender
	}
	return 0
}

func (x *PokemonDetails) GetCp() int32 {
	if x != nil && x.Cp != nil {
		return *x.Cp
	}
	return 0
}

func (x *PokemonDetails) GetAtkIv() int32 {
	if x != nil && x.AtkIv != nil {
		return *x.AtkIv
	}
	return 0
}

func (x *PokemonDetails) GetDefIv() int32 {
	if x != nil && x.DefIv != nil {
		return *x.DefIv
	}
	return 0
}

func (x *PokemonDetails) GetStaIv() int32 {
	if x != nil && x.StaIv != nil {
		return *x.StaIv
	}
	return 0
}

func (x *PokemonDetails) GetIv() float32 {
	if x != nil && x.Iv != nil {
		return *x.Iv
	}
	return 0
}

func (x *PokemonDetails) GetForm() int32 {
	if x != nil && x.Form != nil {
		return *x.Form
	}
	return 0
}

func (x *PokemonDetails) GetLevel() int32 {
	if x != nil && x.Level != nil {
		return *x.Level
	}
	return 0
}

func (x *PokemonDetails) GetEncounterWeather() int32 {
	if x != nil && x.EncounterWeather != nil {
		return *x.EncounterWeather
	}
	return 0
}

func (x *PokemonDetails) GetWeather() int32 {
	if x != nil && x.Weather != nil {
		return *x.Weather
	}
	return 0
}

func (x *PokemonDetails) GetCostume() int32 {
	if x != nil && x.Costume != nil {
		return *x.Costume
	}
	return 0
}

func (x *PokemonDetails) GetFirstSeenTimestamp() int64 {
	if x != nil && x.FirstSeenTimestamp != nil {
		return *x.FirstSeenTimestamp
	}
	return 0
}

func (x *PokemonDetails) GetChanged() int32 {
	if x != nil && x.Changed != nil {
		return *x.Changed
	}
	return 0
}

func (x *PokemonDetails) GetCellId() int64 {
	if x != nil && x.CellId != nil {
		return *x.CellId
	}
	return 0
}

func (x *PokemonDetails) GetExpireTimestampVerified() bool {
	if x != nil {
		return x.ExpireTimestampVerified
	}
	return false
}

func (x *PokemonDetails) GetDisplayPokemonId() int32 {
	if x != nil && x.DisplayPokemonId != nil {
		return *x.DisplayPokemonId
	}
	return 0
}

func (x *PokemonDetails) GetIsDitto() bool {
	if x != nil && x.IsDitto != nil {
		return *x.IsDitto
	}
	return false
}

func (x *PokemonDetails) GetSeenType() string {
	if x != nil && x.SeenType != nil {
		return *x.SeenType
	}
	return ""
}

func (x *PokemonDetails) GetShiny() bool {
	if x != nil && x.Shiny != nil {
		return *x.Shiny
	}
	return false
}

func (x *PokemonDetails) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *PokemonDetails) GetCapture_1() float32 {
	if x != nil && x.Capture_1 != nil {
		return *x.Capture_1
	}
	return 0
}

func (x *PokemonDetails) GetCapture_2() float32 {
	if x != nil && x.Capture_2 != nil {
		return *x.Capture_2
	}
	return 0
}

func (x *PokemonDetails) GetCapture_3() float32 {
	if x != nil && x.Capture_3 != nil {
		return *x.Capture_3
	}
	return 0
}

func (x *PokemonDetails) GetPvp() string {
	if x != nil && x.Pvp != nil {
		return *x.Pvp
	}
	return ""
}

func (x *PokemonDetails) GetDistance() float32 {
	if x != nil && x.Distance != nil {
		return *x.Distance
	}
	return 0
}

var File_grpc_pokemon_api_proto protoreflect.FileDescriptor

const file_grpc_pokemon_api_proto_rawDesc = "" +
	"\n" +
	"\x16grpc/pokemon_api.proto\x12\vpokemon_api\"\xc1\x01\n" +
	"\x12PokemonScanRequest\x12\x17\n" +
	"\amin_lat\x18\x01 \x01(\x02R\x06minLat\x12\x17\n" +
	"\amin_lon\x18\x02 \x01(\x02R\x06minLon\x12\x17\n" +
	"\amax_lat\x18\x03 \x01(\x02R\x06maxLat\x12\x17\n" +
	"\amax_lon\x18\x04 \x01(\x02R\x06maxLon\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x05R\x05limit\x121\n" +
	"\afilters\x18\a \x03(\v2\x17.pokemon_api.PokemonDnfR\afilters\"\xc5\x01\n" +
	"\x14PokemonScanRequestV3\x12\x17\n" +
	"\amin_lat\x18\x01 \x01(\x02R\x06minLat\x12\x17\n" +
	"\amin_lon\x18\x02 \x01(\x02R\x06minLon\x12\x17\n" +
	"\amax_lat\x18\x03 \x01(\x02R\x06maxLat\x12\x17\n" +
	"\amax_lon\x18\x04 \x01(\x02R\x06maxLon\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x05R\x05limit\x123\n" +
	"\afilters\x18\a \x03(\v2\x19.pokemon_api.PokemonDnfV3R\afilters\"\xbe\x06\n" +
	"\n" +
	"PokemonDnf\x120\n" +
	"\apokemon\x18\x01 \x03(\v2\x16.pokemon_api.PokemonIdR\apokemon\x12-\n" +
	"\x02Iv\x18\x02 \x01(\v2\x18.pokemon_api.RangeMinMaxH\x00R\x02Iv\x88\x01\x01\x123\n" +
	"\x05AtkIv\x18\x03 \x01(\v2\x18.pokemon_api.RangeMinMaxH\x01R\x05AtkIv\x88\x01\x01\x123\n" +
	"\x05DefIv\x18\x04 \x01(\v2\x18.pokemon_api.RangeMinMaxH\x02R\x05DefIv\x88\x01\x01\x123\n" +
	"\x05StaIv\x18\x05 \x01(\v2\x18.pokemon_api.RangeMinMaxH\x03R\x05StaIv\x88\x01\x01\x123\n" +
	"\x05Level\x18\x06 \x01(\v2\x18.pokemon_api.RangeMinMaxH\x04R\x05Level\x88\x01\x01\x12-\n" +
	"\x02Cp\x18\a \x01(\v2\x18.pokemon_api.RangeMinMaxH\x05R\x02Cp\x88\x01\x01\x125\n" +
	"\x06Gender\x18\b \x01(\v2\x18.pokemon_api.RangeMinMaxH\x06R\x06Gender\x88\x01\x01\x121\n" +
	"\x04Size\x18\t \x01(\v2\x18.pokemon_api.RangeMinMaxH\aR\x04Size\x88\x01\x01\x12I\n" +
	"\x10PvpLittleRanking\x18\n" +
	" \x01(\v2\x18.pokemon_api.RangeMinMaxH\bR\x10PvpLittleRanking\x88\x01\x01\x12G\n" +
	"\x0fPvpGreatRanking\x18\v \x01(\v2\x18.pokemon_api.RangeMinMaxH\tR\x0fPvpGreatRanking\x88\x01\x01\x12G\n" +
	"\x0fPvpUltraRanking\x18\f \x01(\v2\x18.pokemon_api.RangeMinMaxH\n" +
	"R\x0fPvpUltraRanking\x88\x01\x01B\x05\n" +
	"\x03_IvB\b\n" +
	"\x06_AtkIvB\b\n" +
	"\x06_DefIvB\b\n" +
	"\x06_StaIvB\b\n" +
	"\x06_LevelB\x05\n" +
	"\x03_CpB\t\n" +
	"\a_GenderB\a\n" +
	"\x05_SizeB\x13\n" +
	"\x11_PvpLittleRankingB\x12\n" +
	"\x10_PvpGreatRankingB\x12\n" +
	"\x10_PvpUltraRanking\"\x96\x06\n" +
	"\fPokemonDnfV3\x120\n" +
	"\apokemon\x18\x01 \x03(\v2\x16.pokemon_api.PokemonIdR\apokemon\x12-\n" +
	"\x02Iv\x18\x02 \x01(\v2\x18.pokemon_api.RangeMinMaxH\x00R\x02Iv\x88\x01\x01\x123\n" +
	"\x05AtkIv\x18\x03 \x01(\v2\x18.pokemon_api.RangeMinMaxH\x01R\x05AtkIv\x88\x01\x01\x123\n" +
	"\x05DefIv\x18\x04 \x01(\v2\x18.pokemon_api.RangeMinMaxH\x02R\x05DefIv\x88\x01\x01\x123\n" +
	"\x05StaIv\x18\x05 \x01(\v2\x18.pokemon_api.RangeMinMaxH\x03R\x05StaIv\x88\x01\x01\x123\n" +
	"\x05Level\x18\x06 \x01(\v2\x18.pokemon_api.RangeMinMaxH\x04R\x05Level\x88\x01\x01\x12-\n" +
	"\x02Cp\x18\a \x01(\v2\x18.pokemon_api.RangeMinMaxH\x05R\x02Cp\x88\x01\x01\x12\x16\n" +
	"\x06Gender\x18\b \x03(\x05R\x06Gender\x121\n" +
	"\x04Size\x18\t \x01(\v2\x18.pokemon_api.RangeMinMaxH\x06R\x04Size\x88\x01\x01\x12I\n" +
	"\x10PvpLittleRanking\x18\n" +
	" \x01(\v2\x18.pokemon_api.RangeMinMaxH\aR\x10PvpLittleRanking\x88\x01\x01\x12G\n" +
	"\x0fPvpGreatRanking\x18\v \x01(\v2\x18.pokemon_api.RangeMinMaxH\bR\x0fPvpGreatRanking\x88\x01\x01\x12G\n" +
	"\x0fPvpUltraRanking\x18\f \x01(\v2\x18.pokemon_api.RangeMinMaxH\tR\x0fPvpUltraRanking\x88\x01\x01B\x05\n" +
	"\x03_IvB\b\n" +
	"\x06_AtkIvB\b\n" +
	"\x06_DefIvB\b\n" +
	"\x06_StaIvB\b\n" +
	"\x06_LevelB\x05\n" +
	"\x03_CpB\a\n" +
	"\x05_SizeB\x13\n" +
	"\x11_PvpLittleRankingB\x12\n" +
	"\x10_PvpGreatRankingB\x12\n" +
	"\x10_PvpUltraRanking\"I\n" +
	"\tPokemonId\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x05H\x00R\x02id\x88\x01\x01\x12\x17\n" +
	"\x04form\x18\x02 \x01(\x05H\x01R\x04form\x88\x01\x01B\x05\n" +
	"\x03_idB\a\n" +
	"\x05_form\"K\n" +
	"\vRangeMinMax\x12\x15\n" +
	"\x03min\x18\x01 \x01(\x05H\x00R\x03min\x88\x01\x01\x12\x15\n" +
	"\x03max\x18\x02 \x01(\x05H\x01R\x03max\x88\x01\x01B\x06\n" +
	"\x04_minB\x06\n" +
	"\x04_max\"\xb0\x01\n" +
	"\x13PokemonScanResponse\x12?\n" +
	"\x06status\x18\x01 \x01(\x0e2'.pokemon_api.PokemonScanResponse.StatusR\x06status\x125\n" +
	"\apokemon\x18\x02 \x03(\v2\x1b.pokemon_api.PokemonDetailsR\apokemon\"!\n" +
	"\x06Status\x12\t\n" +
	"\x05UNSET\x10\x00\x12\f\n" +
	"\aSUCCESS\x10\xc8\x01\"\x80\x02\n" +
	"\x15PokemonScanResponseV3\x12A\n" +
	"\x06status\x18\x01 \x01(\x0e2).pokemon_api.PokemonScanResponseV3.StatusR\x06status\x125\n" +
	"\apokemon\x18\x02 \x03(\v2\x1b.pokemon_api.PokemonDetailsR\apokemon\x12\x1a\n" +
	"\bexamined\x18\x03 \x01(\x05R\bexamined\x12\x18\n" +
	"\askipped\x18\x04 \x01(\x05R\askipped\x12\x14\n" +
	"\x05total\x18\x05 \x01(\x05R\x05total\"!\n" +
	"\x06Status\x12\t\n" +
	"\x05UNSET\x10\x00\x12\f\n" +
	"\aSUCCESS\x10\xc8\x01\"\xfc\f\n" +
	"\x0ePokemonDetails\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12$\n" +
	"\vpokestop_id\x18\x02 \x01(\tH\x00R\n" +
	"pokestopId\x88\x01\x01\x12\x1e\n" +
	"\bspawn_id\x18\x03 \x01(\x03H\x01R\aspawnId\x88\x01\x01\x12\x10\n" +
	"\x03lat\x18\x04 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x05 \x01(\x01R\x03lon\x12\x1b\n" +
	"\x06weight\x18\x06 \x01(\x02H\x02R\x06weight\x88\x01\x01\x12\x17\n" +
	"\x04size\x18\a \x01(\x05H\x03R\x04size\x88\x01\x01\x12\x1b\n" +
	"\x06height\x18\b \x01(\x02H\x04R\x06height\x88\x01\x01\x12.\n" +
	"\x10expire_timestamp\x18\t \x01(\x05H\x05R\x0fexpireTimestamp\x88\x01\x01\x12\x1d\n" +
	"\aupdated\x18\n" +
	" \x01(\x05H\x06R\aupdated\x88\x01\x01\x12\"\n" +
	"\n" +
	"pokemon_id\x18\v \x01(\x05H\aR\tpokemonId\x88\x01\x01\x12\x1a\n" +
	"\x06move_1\x18\f \x01(\x05H\bR\x05move1\x88\x01\x01\x12\x1a\n" +
	"\x06move_2\x18\r \x01(\x05H\tR\x05move2\x88\x01\x01\x12\x1b\n" +
	"\x06gender\x18\x0e \x01(\x05H\n" +
	"R\x06gender\x88\x01\x01\x12\x13\n" +
	"\x02cp\x18\x0f \x01(\x05H\vR\x02cp\x88\x01\x01\x12\x1a\n" +
	"\x06atk_iv\x18\x10 \x01(\x05H\fR\x05atkIv\x88\x01\x01\x12\x1a\n" +
	"\x06def_iv\x18\x11 \x01(\x05H\rR\x05defIv\x88\x01\x01\x12\x1a\n" +
	"\x06sta_iv\x18\x12 \x01(\x05H\x0eR\x05staIv\x88\x01\x01\x12\x13\n" +
	"\x02iv\x18\x13 \x01(\x02H\x0fR\x02iv\x88\x01\x01\x12\x17\n" +
	"\x04form\x18\x14 \x01(\x05H\x10R\x04form\x88\x01\x01\x12\x19\n" +
	"\x05level\x18\x15 \x01(\x05H\x11R\x05level\x88\x01\x01\x120\n" +
	"\x11encounter_weather\x18\x16 \x01(\x05H\x12R\x10encounterWeather\x88\x01\x01\x12\x1d\n" +
	"\aweather\x18\x17 \x01(\x05H\x13R\aweather\x88\x01\x01\x12\x1d\n" +
	"\acostume\x18\x18 \x01(\x05H\x14R\acostume\x88\x01\x01\x125\n" +
	"\x14first_seen_timestamp\x18\x19 \x01(\x03H\x15R\x12firstSeenTimestamp\x88\x01\x01\x12\x1d\n" +
	"\achanged\x18\x1a \x01(\x05H\x16R\achanged\x88\x01\x01\x12\x1c\n" +
	"\acell_id\x18\x1b \x01(\x03H\x17R\x06cellId\x88\x01\x01\x12:\n" +
	"\x19expire_timestamp_verified\x18\x1c \x01(\bR\x17expireTimestampVerified\x121\n" +
	"\x12display_pokemon_id\x18\x1d \x01(\x05H\x18R\x10displayPokemonId\x88\x01\x01\x12\x1e\n" +
	"\bis_ditto\x18\x1e \x01(\bH\x19R\aisDitto\x88\x01\x01\x12 \n" +
	"\tseen_type\x18\x1f \x01(\tH\x1aR\bseenType\x88\x01\x01\x12\x19\n" +
	"\x05shiny\x18  \x01(\bH\x1bR\x05shiny\x88\x01\x01\x12\x1f\n" +
	"\busername\x18! \x01(\tH\x1cR\busername\x88\x01\x01\x12 \n" +
	"\tcapture_1\x18\" \x01(\x02H\x1dR\bcapture1\x88\x01\x01\x12 \n" +
	"\tcapture_2\x18# \x01(\x02H\x1eR\bcapture2\x88\x01\x01\x12 \n" +
	"\tcapture_3\x18$ \x01(\x02H\x1fR\bcapture3\x88\x01\x01\x12\x15\n" +
	"\x03pvp\x18% \x01(\tH R\x03pvp\x88\x01\x01\x12\x1f\n" +
	"\bdistance\x18& \x01(\x02H!R\bdistance\x88\x01\x01B\x0e\n" +
	"\f_pokestop_idB\v\n" +
	"\t_spawn_idB\t\n" +
	"\a_weightB\a\n" +
	"\x05_sizeB\t\n" +
	"\a_heightB\x13\n" +
	"\x11_expire_timestampB\n" +
	"\n" +
	"\b_updatedB\r\n" +
	"\v_pokemon_idB\t\n" +
	"\a_move_1B\t\n" +
	"\a_move_2B\t\n" +
	"\a_genderB\x05\n" +
	"\x03_cpB\t\n" +
	"\a_atk_ivB\t\n" +
	"\a_def_ivB\t\n" +
	"\a_sta_ivB\x05\n" +
	"\x03_ivB\a\n" +
	"\x05_formB\b\n" +
	"\x06_levelB\x14\n" +
	"\x12_encounter_weatherB\n" +
	"\n" +
	"\b_weatherB\n" +
	"\n" +
	"\b_costumeB\x17\n" +
	"\x15_first_seen_timestampB\n" +
	"\n" +
	"\b_changedB\n" +
	"\n" +
	"\b_cell_idB\x15\n" +
	"\x13_display_pokemon_idB\v\n" +
	"\t_is_dittoB\f\n" +
	"\n" +
	"_seen_typeB\b\n" +
	"\x06_shinyB\v\n" +
	"\t_usernameB\f\n" +
	"\n" +
	"_capture_1B\f\n" +
	"\n" +
	"_capture_2B\f\n" +
	"\n" +
	"_capture_3B\x06\n" +
	"\x04_pvpB\v\n" +
	"\t_distance2\xad\x01\n" +
	"\aPokemon\x12M\n" +
	"\x06Search\x12\x1f.pokemon_api.PokemonScanRequest\x1a .pokemon_api.PokemonScanResponse\"\x00\x12S\n" +
	"\bSearchV3\x12!.pokemon_api.PokemonScanRequestV3\x1a\".pokemon_api.PokemonScanResponseV3\"\x00B\"Z github.com/unownhash/golbat/grpcb\x06proto3"

var (
	file_grpc_pokemon_api_proto_rawDescOnce sync.Once
	file_grpc_pokemon_api_proto_rawDescData []byte
)

func file_grpc_pokemon_api_proto_rawDescGZIP() []byte {
	file_grpc_pokemon_api_proto_rawDescOnce.Do(func() {
		file_grpc_pokemon_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_pokemon_api_proto_rawDesc), len(file_grpc_pokemon_api_proto_rawDesc)))
	})
	return file_grpc_pokemon_api_proto_rawDescData
}

var file_grpc_pokemon_api_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_grpc_pokemon_api_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_grpc_pokemon_api_proto_goTypes = []any{
	(PokemonScanResponse_Status)(0),   // 0: pokemon_api.PokemonScanResponse.Status
	(PokemonScanResponseV3_Status)(0), // 1: pokemon_api.PokemonScanResponseV3.Status
	(*PokemonScanRequest)(nil),        // 2: pokemon_api.PokemonScanRequest
	(*PokemonScanRequestV3)(nil),      // 3: pokemon_api.PokemonScanRequestV3
	(*PokemonDnf)(nil),                // 4: pokemon_api.PokemonDnf
	(*PokemonDnfV3)(nil),              // 5: pokemon_api.PokemonDnfV3
	(*PokemonId)(nil),                 // 6: pokemon_api.PokemonId
	(*RangeMinMax)(nil),               // 7: pokemon_api.RangeMinMax
	(*PokemonScanResponse)(nil),       // 8: pokemon_api.PokemonScanResponse
	(*PokemonScanResponseV3)(nil),     // 9: pokemon_api.PokemonScanResponseV3
	(*PokemonDetails)(nil),            // 10: pokemon_api.PokemonDetails
}
var file_grpc_pokemon_api_proto_depIdxs = []int32{
	4,  // 0: pokemon_api.PokemonScanRequest.filters:type_name -> pokemon_api.PokemonDnf
	5,  // 1: pokemon_api.PokemonScanRequestV3.filters:type_name -> pokemon_api.PokemonDnfV3
	6,  // 2: pokemon_api.PokemonDnf.pokemon:type_name -> pokemon_api.PokemonId
	7,  // 3: pokemon_api.PokemonDnf.Iv:type_name -> pokemon_api.RangeMinMax
	7,  // 4: pokemon_api.PokemonDnf.AtkIv:type_name -> pokemon_api.RangeMinMax
	7,  // 5: pokemon_api.PokemonDnf.DefIv:type_name -> pokemon_api.RangeMinMax
	7,  // 6: pokemon_api.PokemonDnf.StaIv:type_name -> pokemon_api.RangeMinMax
	7,  // 7: pokemon_api.PokemonDnf.Level:type_name -> pokemon_api.RangeMinMax
	7,  // 8: pokemon_api.PokemonDnf.Cp:type_name -> pokemon_api.RangeMinMax
	7,  // 9: pokemon_api.PokemonDnf.Gender:type_name -> pokemon_api.RangeMinMax
	7,  // 10: pokemon_api.PokemonDnf.Size:type_name -> pokemon_api.RangeMinMax
	7,  // 11: pokemon_api.PokemonDnf.PvpLittleRanking:type_name -> pokemon_api.RangeMinMax
	7,  // 12: pokemon_api.PokemonDnf.PvpGreatRanking:type_name -> pokemon_api.RangeMinMax
	7,  // 13: pokemon_api.PokemonDnf.PvpUltraRanking:type_name -> pokemon_api.RangeMinMax
	6,  // 14: pokemon_api.PokemonDnfV3.pokemon:type_name -> pokemon_api.PokemonId
	7,  // 15: pokemon_api.PokemonDnfV3.Iv:type_name -> pokemon_api.RangeMinMax
	7,  // 16: pokemon_api.PokemonDnfV3.AtkIv:type_name -> pokemon_api.RangeMinMax
	7,  // 17: pokemon_api.PokemonDnfV3.DefIv:type_name -> pokemon_api.RangeMinMax
	7,  // 18: pokemon_api.PokemonDnfV3.StaIv:type_name -> pokemon_api.RangeMinMax
	7,  // 19: pokemon_api.PokemonDnfV3.Level:type_name -> pokemon_api.RangeMinMax
	7,  // 20: pokemon_api.PokemonDnfV3.Cp:type_name -> pokemon_api.RangeMinMax
	7,  // 21: pokemon_api.PokemonDnfV3.Size:type_name -> pokemon_api.RangeMinMax
	7,  // 22: pokemon_api.PokemonDnfV3.PvpLittleRanking:type_name -> pokemon_api.RangeMinMax
	7,  // 23: pokemon_api.PokemonDnfV3.PvpGreatRanking:type_name -> pokemon_api.RangeMinMax
	7,  // 24: pokemon_api.PokemonDnfV3.PvpUltraRanking:type_name -> pokemon_api.RangeMinMax
	0,  // 25: pokemon_api.PokemonScanResponse.status:type_name -> pokemon_api.PokemonScanResponse.Status
	10, // 26: pokemon_api.PokemonScanResponse.pokemon:type_name -> pokemon_api.PokemonDetails
	1,  // 27: pokemon_api.PokemonScanResponseV3.status:type_name -> pokemon_api.PokemonScanResponseV3.Status
	10, // 28: pokemon_api.PokemonScanResponseV3.pokemon:type_name -> pokemon_api.PokemonDetails
	2,  // 29: pokemon_api.Pokemon.Search:input_type -> pokemon_api.PokemonScanRequest
	3,  // 30: pokemon_api.Pokemon.SearchV3:input_type -> pokemon_api.PokemonScanRequestV3
	8,  // 31: pokemon_api.Pokemon.Search:output_type -> pokemon_api.PokemonScanResponse
	9,  // 32: pokemon_api.Pokemon.SearchV3:output_type -> pokemon_api.PokemonScanResponseV3
	31, // [31:33] is the sub-list for method output_type
	29, // [29:31] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_grpc_pokemon_api_proto_init() }
func file_grpc_pokemon_api_proto_init() {
	if File_grpc_pokemon_api_proto != nil {
		return
	}
	file_grpc_pokemon_api_proto_msgTypes[2].OneofWrappers = []any{}
	file_grpc_pokemon_api_proto_msgTypes[3].OneofWrappers = []any{}
	file_grpc_pokemon_api_proto_msgTypes[4].OneofWrappers = []any{}
	file_grpc_pokemon_api_proto_msgTypes[5].OneofWrappers = []any{}
	file_grpc_pokemon_api_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_pokemon_api_proto_rawDesc), len(file_grpc_pokemon_api_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_pokemon_api_proto_goTypes,
		DependencyIndexes: file_grpc_pokemon_api_proto_depIdxs,
		EnumInfos:         file_grpc_pokemon_api_proto_enumTypes,
		MessageInfos:      file_grpc_pokemon_api_proto_msgTypes,
	}.Build()
	File_grpc_pokemon_api_proto = out.File
	file_grpc_pokemon_api_proto_goTypes = nil
	file_grpc_pokemon_api_proto_depIdxs = nil
}
