// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        v6.33.1
// source: grpc/raw_receiver.proto

//go:build protoopaque

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RawProtoRequest struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_DeviceId     string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	xxx_hidden_Username     string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	xxx_hidden_TrainerLevel int32                  `protobuf:"varint,3,opt,name=trainer_level,json=trainerLevel,proto3" json:"trainer_level,omitempty"`
	xxx_hidden_LatTarget    float32                `protobuf:"fixed32,4,opt,name=lat_target,json=latTarget,proto3" json:"lat_target,omitempty"`
	xxx_hidden_LonTarget    float32                `protobuf:"fixed32,5,opt,name=lon_target,json=lonTarget,proto3" json:"lon_target,omitempty"`
	xxx_hidden_Timestamp    int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	xxx_hidden_HaveAr       bool                   `protobuf:"varint,7,opt,name=have_ar,json=haveAr,proto3,oneof" json:"have_ar,omitempty"`
	xxx_hidden_Contents     *[]*Content            `protobuf:"bytes,8,rep,name=contents,proto3" json:"contents,omitempty"`
	xxx_hidden_ScanContext  *string                `protobuf:"bytes,9,opt,name=scan_context,json=scanContext,proto3,oneof" json:"scan_context,omitempty"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *RawProtoRequest) Reset() {
	*x = RawProtoRequest{}
	mi := &file_grpc_raw_receiver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawProtoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawProtoRequest) ProtoMessage() {}

func (x *RawProtoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_raw_receiver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RawProtoRequest) GetDeviceId() string {
	if x != nil {
		return x.xxx_hidden_DeviceId
	}
	return ""
}

func (x *RawProtoRequest) GetUsername() string {
	if x != nil {
		return x.xxx_hidden_Username
	}
	return ""
}

func (x *RawProtoRequest) GetTrainerLevel() int32 {
	if x != nil {
		return x.xxx_hidden_TrainerLevel
	}
	return 0
}

func (x *RawProtoRequest) GetLatTarget() float32 {
	if x != nil {
		return x.xxx_hidden_LatTarget
	}
	return 0
}

func (x *RawProtoRequest) GetLonTarget() float32 {
	if x != nil {
		return x.xxx_hidden_LonTarget
	}
	return 0
}

func (x *RawProtoRequest) GetTimestamp() int64 {
	if x != nil {
		return x.xxx_hidden_Timestamp
	}
	return 0
}

func (x *RawProtoRequest) GetHaveAr() bool {
	if x != nil {
		return x.xxx_hidden_HaveAr
	}
	return false
}

func (x *RawProtoRequest) GetContents() []*Content {
	if x != nil {
		if x.xxx_hidden_Contents != nil {
			return *x.xxx_hidden_Contents
		}
	}
	return nil
}

func (x *RawProtoRequest) GetScanContext() string {
	if x != nil {
		if x.xxx_hidden_ScanContext != nil {
			return *x.xxx_hidden_ScanContext
		}
		return ""
	}
	return ""
}

func (x *RawProtoRequest) SetDeviceId(v string) {
	x.xxx_hidden_DeviceId = v
}

func (x *RawProtoRequest) SetUsername(v string) {
	x.xxx_hidden_Username = v
}

func (x *RawProtoRequest) SetTrainerLevel(v int32) {
	x.xxx_hidden_TrainerLevel = v
}

func (x *RawProtoRequest) SetLatTarget(v float32) {
	x.xxx_hidden_LatTarget = v
}

func (x *RawProtoRequest) SetLonTarget(v float32) {
	x.xxx_hidden_LonTarget = v
}

func (x *RawProtoRequest) SetTimestamp(v int64) {
	x.xxx_hidden_Timestamp = v
}

func (x *RawProtoRequest) SetHaveAr(v bool) {
	x.xxx_hidden_HaveAr = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 9)
}

func (x *RawProtoRequest) SetContents(v []*Content) {
	x.xxx_hidden_Contents = &v
}

func (x *RawProtoRequest) SetScanContext(v string) {
	x.xxx_hidden_ScanContext = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 9)
}

func (x *RawProtoRequest) HasHaveAr() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *RawProtoRequest) HasScanContext() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *RawProtoRequest) ClearHaveAr() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_HaveAr = false
}

func (x *RawProtoRequest) ClearScanContext() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_ScanContext = nil
}

type RawProtoRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	DeviceId     string
	Username     string
	TrainerLevel int32
	LatTarget    float32
	LonTarget    float32
	Timestamp    int64
	HaveAr       *bool
	Contents     []*Content
	ScanContext  *string
}

func (b0 RawProtoRequest_builder) Build() *RawProtoRequest {
	m0 := &RawProtoRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_DeviceId = b.DeviceId
	x.xxx_hidden_Username = b.Username
	x.xxx_hidden_TrainerLevel = b.TrainerLevel
	x.xxx_hidden_LatTarget = b.LatTarget
	x.xxx_hidden_LonTarget = b.LonTarget
	x.xxx_hidden_Timestamp = b.Timestamp
	if b.HaveAr != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 9)
		x.xxx_hidden_HaveAr = *b.HaveAr
	}
	x.xxx_hidden_Contents = &b.Contents
	if b.ScanContext != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 9)
		x.xxx_hidden_ScanContext = b.ScanContext
	}
	return m0
}

type Content struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ResponsePayload []byte                 `protobuf:"bytes,1,opt,name=response_payload,json=responsePayload,proto3" json:"response_payload,omitempty"`
	xxx_hidden_RequestPayload  []byte                 `protobuf:"bytes,2,opt,name=request_payload,json=requestPayload,proto3,oneof" json:"request_payload,omitempty"`
	xxx_hidden_Method          int32                  `protobuf:"varint,3,opt,name=method,proto3" json:"method,omitempty"`
	xxx_hidden_HaveAr          bool                   `protobuf:"varint,4,opt,name=have_ar,json=haveAr,proto3,oneof" json:"have_ar,omitempty"`
	XXX_raceDetectHookData     protoimpl.RaceDetectHookData
	XXX_presence               [1]uint32
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *Content) Reset() {
	*x = Content{}
	mi := &file_grpc_raw_receiver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Content) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Content) ProtoMessage() {}

func (x *Content) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_raw_receiver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Content) GetResponsePayload() []byte {
	if x != nil {
		return x.xxx_hidden_ResponsePayload
	}
	return nil
}

func (x *Content) GetRequestPayload() []byte {
	if x != nil {
		return x.xxx_hidden_RequestPayload
	}
	return nil
}

func (x *Content) GetMethod() int32 {
	if x != nil {
		return x.xxx_hidden_Method
	}
	return 0
}

func (x *Content) GetHaveAr() bool {
	if x != nil {
		return x.xxx_hidden_HaveAr
	}
	return false
}

func (x *Content) SetResponsePayload(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_ResponsePayload = v
}

func (x *Content) SetRequestPayload(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_RequestPayload = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *Content) SetMethod(v int32) {
	x.xxx_hidden_Method = v
}

func (x *Content) SetHaveAr(v bool) {
	x.xxx_hidden_HaveAr = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *Content) HasRequestPayload() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Content) HasHaveAr() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Content) ClearRequestPayload() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_RequestPayload = nil
}

func (x *Content) ClearHaveAr() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_HaveAr = false
}

type Content_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ResponsePayload []byte
	RequestPayload  []byte
	Method          int32
	HaveAr          *bool
}

func (b0 Content_builder) Build() *Content {
	m0 := &Content{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ResponsePayload = b.ResponsePayload
	if b.RequestPayload != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_RequestPayload = b.RequestPayload
	}
	x.xxx_hidden_Method = b.Method
	if b.HaveAr != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_HaveAr = *b.HaveAr
	}
	return m0
}

type RawProtoResponse struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Message string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RawProtoResponse) Reset() {
	*x = RawProtoResponse{}
	mi := &file_grpc_raw_receiver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawProtoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawProtoResponse) ProtoMessage() {}

func (x *RawProtoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_raw_receiver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RawProtoResponse) GetMessage() string {
	if x != nil {
		return x.xxx_hidden_Message
	}
	return ""
}

func (x *RawProtoResponse) SetMessage(v string) {
	x.xxx_hidden_Message = v
}

type RawProtoResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Message string
}

func (b0 RawProtoResponse_builder) Build() *RawProtoResponse {
	m0 := &RawProtoResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Message = b.Message
	return m0
}

var File_grpc_raw_receiver_proto protoreflect.FileDescriptor

var file_grpc_raw_receiver_proto_rawDesc = []byte{
	0x0a, 0x17, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x72, 0x61, 0x77, 0x5f, 0x72, 0x65, 0x63, 0x65, 0x69,
	0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x72, 0x61, 0x77, 0x5f, 0x72,
	0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x22, 0xe1, 0x02, 0x0a, 0x0f, 0x52, 0x61, 0x77, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x64,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x5f,
	0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x74, 0x72, 0x61,
	0x69, 0x6e, 0x65, 0x72, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x61, 0x74,
	0x5f, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x6c,
	0x61, 0x74, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x6f, 0x6e, 0x5f,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x6c, 0x6f,
	0x6e, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1c, 0x0a, 0x07, 0x68, 0x61, 0x76, 0x65, 0x5f, 0x61, 0x72,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x06, 0x68, 0x61, 0x76, 0x65, 0x41, 0x72,
	0x88, 0x01, 0x01, 0x12, 0x31, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x18,
	0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x72, 0x61, 0x77, 0x5f, 0x72, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x72, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x08, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x26, 0x0a, 0x0c, 0x73, 0x63, 0x61, 0x6e, 0x5f, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x0b,
	0x73, 0x63, 0x61, 0x6e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x88, 0x01, 0x01, 0x42, 0x0a,
	0x0a, 0x08, 0x5f, 0x68, 0x61, 0x76, 0x65, 0x5f, 0x61, 0x72, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x73,
	0x63, 0x61, 0x6e, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x22, 0xb8, 0x01, 0x0a, 0x07,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x29, 0x0a, 0x10, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x5f, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x0f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x12, 0x2c, 0x0a, 0x0f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x0e, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x88, 0x01, 0x01,
	0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x1c, 0x0a, 0x07, 0x68, 0x61, 0x76, 0x65,
	0x5f, 0x61, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x48, 0x01, 0x52, 0x06, 0x68, 0x61, 0x76,
	0x65, 0x41, 0x72, 0x88, 0x01, 0x01, 0x42, 0x12, 0x0a, 0x10, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x5f, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x68,
	0x61, 0x76, 0x65, 0x5f, 0x61, 0x72, 0x22, 0x2c, 0x0a, 0x10, 0x52, 0x61, 0x77, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x32, 0x5d, 0x0a, 0x08, 0x52, 0x61, 0x77, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x51, 0x0a, 0x0e, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x52, 0x61, 0x77, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x1d, 0x2e, 0x72, 0x61, 0x77, 0x5f, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65,
	0x72, 0x2e, 0x52, 0x61, 0x77, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1e, 0x2e, 0x72, 0x61, 0x77, 0x5f, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72,
	0x2e, 0x52, 0x61, 0x77, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x22, 0x5a, 0x20, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x75, 0x6e, 0x6f, 0x77, 0x6e, 0x68, 0x61, 0x73, 0x68, 0x2f, 0x67, 0x6f, 0x6c, 0x62,
	0x61, 0x74, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var file_grpc_raw_receiver_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_grpc_raw_receiver_proto_goTypes = []any{
	(*RawProtoRequest)(nil),  // 0: raw_receiver.RawProtoRequest
	(*Content)(nil),          // 1: raw_receiver.Content
	(*RawProtoResponse)(nil), // 2: raw_receiver.RawProtoResponse
}
var file_grpc_raw_receiver_proto_depIdxs = []int32{
	1, // 0: raw_receiver.RawProtoRequest.contents:type_name -> raw_receiver.Content
	0, // 1: raw_receiver.RawProto.SubmitRawProto:input_type -> raw_receiver.RawProtoRequest
	2, // 2: raw_receiver.RawProto.SubmitRawProto:output_type -> raw_receiver.RawProtoResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_grpc_raw_receiver_proto_init() }
func file_grpc_raw_receiver_proto_init() {
	if File_grpc_raw_receiver_proto != nil {
		return
	}
	file_grpc_raw_receiver_proto_msgTypes[0].OneofWrappers = []any{}
	file_grpc_raw_receiver_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_raw_receiver_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_raw_receiver_proto_goTypes,
		DependencyIndexes: file_grpc_raw_receiver_proto_depIdxs,
		MessageInfos:      file_grpc_raw_receiver_proto_msgTypes,
	}.Build()
	File_grpc_raw_receiver_proto = out.File
	file_grpc_raw_receiver_proto_rawDesc = nil
	file_grpc_raw_receiver_proto_goTypes = nil
	file_grpc_raw_receiver_proto_depIdxs = nil
}
