// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.15.8
// source: grpc/raw_receiver.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RawProtoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	TrainerLevel  int32                  `protobuf:"varint,3,opt,name=trainer_level,json=trainerLevel,proto3" json:"trainer_level,omitempty"`
	LatTarget     float32                `protobuf:"fixed32,4,opt,name=lat_target,json=latTarget,proto3" json:"lat_target,omitempty"`
	LonTarget     float32                `protobuf:"fixed32,5,opt,name=lon_target,json=lonTarget,proto3" json:"lon_target,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	HaveAr        *bool                  `protobuf:"varint,7,opt,name=have_ar,json=haveAr,proto3,oneof" json:"have_ar,omitempty"`
	Contents      []*Content             `protobuf:"bytes,8,rep,name=contents,proto3" json:"contents,omitempty"`
	ScanContext   *string                `protobuf:"bytes,9,opt,name=scan_context,json=scanContext,proto3,oneof" json:"scan_context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawProtoRequest) Reset() {
	*x = RawProtoRequest{}
	mi := &file_grpc_raw_receiver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawProtoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawProtoRequest) ProtoMessage() {}

func (x *RawProtoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_raw_receiver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawProtoRequest.ProtoReflect.Descriptor instead.
func (*RawProtoRequest) Descriptor() ([]byte, []int) {
	return file_grpc_raw_receiver_proto_rawDescGZIP(), []int{0}
}

func (x *RawProtoRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *RawProtoRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RawProtoRequest) GetTrainerLevel() int32 {
	if x != nil {
		return x.TrainerLevel
	}
	return 0
}

func (x *RawProtoRequest) GetLatTarget() float32 {
	if x != nil {
		return x.LatTarget
	}
	return 0
}

func (x *RawProtoRequest) GetLonTarget() float32 {
	if x != nil {
		return x.LonTarget
	}
	return 0
}

func (x *RawProtoRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *RawProtoRequest) GetHaveAr() bool {
	if x != nil && x.HaveAr != nil {
		return *x.HaveAr
	}
	return false
}

func (x *RawProtoRequest) GetContents() []*Content {
	if x != nil {
		return x.Contents
	}
	return nil
}

func (x *RawProtoRequest) GetScanContext() string {
	if x != nil && x.ScanContext != nil {
		return *x.ScanContext
	}
	return ""
}

type Content struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ResponsePayload []byte                 `protobuf:"bytes,1,opt,name=response_payload,json=responsePayload,proto3" json:"response_payload,omitempty"`
	RequestPayload  []byte                 `protobuf:"bytes,2,opt,name=request_payload,json=requestPayload,proto3,oneof" json:"request_payload,omitempty"`
	Method          int32                  `protobuf:"varint,3,opt,name=method,proto3" json:"method,omitempty"`
	HaveAr          *bool                  `protobuf:"varint,4,opt,name=have_ar,json=haveAr,proto3,oneof" json:"have_ar,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Content) Reset() {
	*x = Content{}
	mi := &file_grpc_raw_receiver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Content) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Content) ProtoMessage() {}

func (x *Content) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_raw_receiver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Content.ProtoReflect.Descriptor instead.
func (*Content) Descriptor() ([]byte, []int) {
	return file_grpc_raw_receiver_proto_rawDescGZIP(), []int{1}
}

func (x *Content) GetResponsePayload() []byte {
	if x != nil {
		return x.ResponsePayload
	}
	return nil
}

func (x *Content) GetRequestPayload() []byte {
	if x != nil {
		return x.RequestPayload
	}
	return nil
}

func (x *Content) GetMethod() int32 {
	if x != nil {
		return x.Method
	}
	return 0
}

func (x *Content) GetHaveAr() bool {
	if x != nil && x.HaveAr != nil {
		return *x.HaveAr
	}
	return false
}

type RawProtoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawProtoResponse) Reset() {
	*x = RawProtoResponse{}
	mi := &file_grpc_raw_receiver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawProtoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawProtoResponse) ProtoMessage() {}

func (x *RawProtoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_raw_receiver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawProtoResponse.ProtoReflect.Descriptor instead.
func (*RawProtoResponse) Descriptor() ([]byte, []int) {
	return file_grpc_raw_receiver_proto_rawDescGZIP(), []int{2}
}

func (x *RawProtoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_grpc_raw_receiver_proto protoreflect.FileDescriptor

const file_grpc_raw_receiver_proto_rawDesc = "" +
	"\n" +
	"\x17grpc/raw_receiver.proto\x12\fraw_receiver\"\xe1\x02\n" +
	"\x0fRawProtoRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12#\n" +
	"\rtrainer_level\x18\x03 \x01(\x05R\ftrainerLevel\x12\x1d\n" +
	"\n" +
	"lat_target\x18\x04 \x01(\x02R\tlatTarget\x12\x1d\n" +
	"\n" +
	"lon_target\x18\x05 \x01(\x02R\tlonTarget\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x12\x1c\n" +
	"\ahave_ar\x18\a \x01(\bH\x00R\x06haveAr\x88\x01\x01\x121\n" +
	"\bcontents\x18\b \x03(\v2\x15.raw_receiver.ContentR\bcontents\x12&\n" +
	"\fscan_context\x18\t \x01(\tH\x01R\vscanContext\x88\x01\x01B\n" +
	"\n" +
	"\b_have_arB\x0f\n" +
	"\r_scan_context\"\xb8\x01\n" +
	"\aContent\x12)\n" +
	"\x10response_payload\x18\x01 \x01(\fR\x0fresponsePayload\x12,\n" +
	"\x0frequest_payload\x18\x02 \x01(\fH\x00R\x0erequestPayload\x88\x01\x01\x12\x16\n" +
	"\x06method\x18\x03 \x01(\x05R\x06method\x12\x1c\n" +
	"\ahave_ar\x18\x04 \x01(\bH\x01R\x06haveAr\x88\x01\x01B\x12\n" +
	"\x10_request_payloadB\n" +
	"\n" +
	"\b_have_ar\",\n" +
	"\x10RawProtoResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2]\n" +
	"\bRawProto\x12Q\n" +
	"\x0eSubmitRawProto\x12\x1d.raw_receiver.RawProtoRequest\x1a\x1e.raw_receiver.RawProtoResponse\"\x00B\"Z github.com/unownhash/golbat/grpcb\x06proto3"

var (
	file_grpc_raw_receiver_proto_rawDescOnce sync.Once
	file_grpc_raw_receiver_proto_rawDescData []byte
)

func file_grpc_raw_receiver_proto_rawDescGZIP() []byte {
	file_grpc_raw_receiver_proto_rawDescOnce.Do(func() {
		file_grpc_raw_receiver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_raw_receiver_proto_rawDesc), len(file_grpc_raw_receiver_proto_rawDesc)))
	})
	return file_grpc_raw_receiver_proto_rawDescData
}

var file_grpc_raw_receiver_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_grpc_raw_receiver_proto_goTypes = []any{
	(*RawProtoRequest)(nil),  // 0: raw_receiver.RawProtoRequest
	(*Content)(nil),          // 1: raw_receiver.Content
	(*RawProtoResponse)(nil), // 2: raw_receiver.RawProtoResponse
}
var file_grpc_raw_receiver_proto_depIdxs = []int32{
	1, // 0: raw_receiver.RawProtoRequest.contents:type_name -> raw_receiver.Content
	0, // 1: raw_receiver.RawProto.SubmitRawProto:input_type -> raw_receiver.RawProtoRequest
	2, // 2: raw_receiver.RawProto.SubmitRawProto:output_type -> raw_receiver.RawProtoResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_grpc_raw_receiver_proto_init() }
func file_grpc_raw_receiver_proto_init() {
	if File_grpc_raw_receiver_proto != nil {
		return
	}
	file_grpc_raw_receiver_proto_msgTypes[0].OneofWrappers = []any{}
	file_grpc_raw_receiver_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_raw_receiver_proto_rawDesc), len(file_grpc_raw_receiver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_raw_receiver_proto_goTypes,
		DependencyIndexes: file_grpc_raw_receiver_proto_depIdxs,
		MessageInfos:      file_grpc_raw_receiver_proto_msgTypes,
	}.Build()
	File_grpc_raw_receiver_proto = out.File
	file_grpc_raw_receiver_proto_goTypes = nil
	file_grpc_raw_receiver_proto_depIdxs = nil
}
